MagicBlock.create({name: "Other"})
MagicBlock.create({name: "Duel Decks"})
MagicBlock.create({name: "From the Vault"})
MagicBlock.create({name: "Premium Deck Series"})
MagicBlock.create({name: "Planechase"})
MagicBlock.create({name: "Commander"})
MagicBlock.create({name: "Masters Editions"})
MagicBlock.create({name: "Core Sets"})
MagicBlock.create({name: "Mirage Block"})
MagicBlock.create({name: "Tempest Block"})
MagicBlock.create({name: "Urza Block"})
MagicBlock.create({name: "Masques Block"})
MagicBlock.create({name: "Invasion Block"})
MagicBlock.create({name: "Odyssey Block"})
MagicBlock.create({name: "Onslaught Block"})
MagicBlock.create({name: "Mirrodin Block"})
MagicBlock.create({name: "Kamigawa Block"})
MagicBlock.create({name: "Ravnica Block"})
MagicBlock.create({name: "Ice Age Block"})
MagicBlock.create({name: "Time Spiral Block"})
MagicBlock.create({name: "Lorwyn-Shadowmoor Block"})
MagicBlock.create({name: "Shards of Alara Block"})
MagicBlock.create({name: "Zendikar Block"})
MagicBlock.create({name: "Scars of Mirrodin Block"})
MagicBlock.create({name: "Innistrad Block"})
MagicBlock.create({name: "Return to Ravnica Block"})
MagicBlock.create({name: "Theros Block"})
MagicBlock.create({name: "Khans of Tarkir Block"})

