MagicCard.create(object_type: "pack", name: "Dark Ascension Booster", mtgo_id: "43532", magic_set_id: MagicSet.find_by(code: "DKA").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Coldsnap Booster", mtgo_id: "24831", magic_set_id: MagicSet.find_by(code: "CSP").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Coldsnap Booster", mtgo_id: "24830", magic_set_id: MagicSet.find_by(code: "CSP").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Coldsnap Booster", mtgo_id: "24829", magic_set_id: MagicSet.find_by(code: "CSP").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Alara Reborn Booster", mtgo_id: "32523", magic_set_id: MagicSet.find_by(code: "ARB").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Apocalypse Booster", mtgo_id: "16352", magic_set_id: MagicSet.find_by(code: "AP").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Avacyn Restored Booster", mtgo_id: "44335", magic_set_id: MagicSet.find_by(code: "AVR").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Betrayers of Kamigawa Booster", mtgo_id: "21921", magic_set_id: MagicSet.find_by(code: "BOK").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Betrayers of Kamigawa Booster", mtgo_id: "21920", magic_set_id: MagicSet.find_by(code: "BOK").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Betrayers of Kamigawa Booster", mtgo_id: "21919", magic_set_id: MagicSet.find_by(code: "BOK").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Born of the Gods Booster", mtgo_id: "51954", magic_set_id: MagicSet.find_by(code: "BNG").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Champions of Kamigawa Booster", mtgo_id: "21583", magic_set_id: MagicSet.find_by(code: "CHK").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Champions of Kamigawa Booster", mtgo_id: "21582", magic_set_id: MagicSet.find_by(code: "CHK").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Champions of Kamigawa Booster", mtgo_id: "21581", magic_set_id: MagicSet.find_by(code: "CHK").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Champions of Kamigawa Booster", mtgo_id: "21580", magic_set_id: MagicSet.find_by(code: "CHK").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Champions of Kamigawa Booster", mtgo_id: "21579", magic_set_id: MagicSet.find_by(code: "CHK").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Conflux Booster", mtgo_id: "31947", magic_set_id: MagicSet.find_by(code: "_CON").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Darksteel Booster", mtgo_id: "20623", magic_set_id: MagicSet.find_by(code: "DST").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Darksteel Booster", mtgo_id: "20622", magic_set_id: MagicSet.find_by(code: "DST").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Darksteel Booster", mtgo_id: "20621", magic_set_id: MagicSet.find_by(code: "DST").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Dissension Booster", mtgo_id: "24391", magic_set_id: MagicSet.find_by(code: "DIS").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Dissension Booster", mtgo_id: "23960", magic_set_id: MagicSet.find_by(code: "DIS").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Dissension Booster", mtgo_id: "23959", magic_set_id: MagicSet.find_by(code: "DIS").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Dragon's Maze Booster", mtgo_id: "48599", magic_set_id: MagicSet.find_by(code: "DGM").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Eighth Edition Booster", mtgo_id: "19664", magic_set_id: MagicSet.find_by(code: "8ED").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Eighth Edition Booster", mtgo_id: "19663", magic_set_id: MagicSet.find_by(code: "8ED").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Eventide Booster", mtgo_id: "30291", magic_set_id: MagicSet.find_by(code: "EVE").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Exodus Booster", mtgo_id: "35197", magic_set_id: MagicSet.find_by(code: "EX").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Fifth Dawn Booster", mtgo_id: "20960", magic_set_id: MagicSet.find_by(code: "5DN").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Fifth Dawn Booster", mtgo_id: "20959", magic_set_id: MagicSet.find_by(code: "5DN").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Fifth Dawn Booster", mtgo_id: "20958", magic_set_id: MagicSet.find_by(code: "5DN").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Future Sight Booster", mtgo_id: "26956", magic_set_id: MagicSet.find_by(code: "FUT").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Future Sight Booster", mtgo_id: "26955", magic_set_id: MagicSet.find_by(code: "FUT").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Future Sight Booster", mtgo_id: "26954", magic_set_id: MagicSet.find_by(code: "FUT").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Gatecrash Booster", mtgo_id: "48026", magic_set_id: MagicSet.find_by(code: "GTC").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Guildpact Booster", mtgo_id: "23945", magic_set_id: MagicSet.find_by(code: "GPT").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Guildpact Booster", mtgo_id: "23944", magic_set_id: MagicSet.find_by(code: "GPT").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Guildpact Booster", mtgo_id: "23943", magic_set_id: MagicSet.find_by(code: "GPT").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Innistrad Booster", mtgo_id: "42832", magic_set_id: MagicSet.find_by(code: "ISD").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Invasion Booster", mtgo_id: "15040", magic_set_id: MagicSet.find_by(code: "IN").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Invasion Booster", mtgo_id: "15039", magic_set_id: MagicSet.find_by(code: "IN").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Invasion Booster", mtgo_id: "15038", magic_set_id: MagicSet.find_by(code: "IN").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Journey into Nyx Booster", mtgo_id: "52358", magic_set_id: MagicSet.find_by(code: "JOU").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Judgment Booster", mtgo_id: "17642", magic_set_id: MagicSet.find_by(code: "JUD").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Khans of Tarkir Booster", mtgo_id: "54536", magic_set_id: MagicSet.find_by(code: "KTK").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Legions Booster", mtgo_id: "18649", magic_set_id: MagicSet.find_by(code: "LGN").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Legions Booster", mtgo_id: "18648", magic_set_id: MagicSet.find_by(code: "LGN").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Legions Booster", mtgo_id: "18647", magic_set_id: MagicSet.find_by(code: "LGN").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Lorwyn Booster", mtgo_id: "28797", magic_set_id: MagicSet.find_by(code: "LRW").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Lorwyn Booster", mtgo_id: "28796", magic_set_id: MagicSet.find_by(code: "LRW").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Lorwyn Booster", mtgo_id: "28795", magic_set_id: MagicSet.find_by(code: "LRW").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Lorwyn Booster", mtgo_id: "28794", magic_set_id: MagicSet.find_by(code: "LRW").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Lorwyn Booster", mtgo_id: "28793", magic_set_id: MagicSet.find_by(code: "LRW").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Magic 2010 Booster", mtgo_id: "33119", magic_set_id: MagicSet.find_by(code: "M10").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Magic 2011 Booster", mtgo_id: "37626", magic_set_id: MagicSet.find_by(code: "M11").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Magic 2012 Booster", mtgo_id: "41617", magic_set_id: MagicSet.find_by(code: "M12").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Magic 2013 Booster", mtgo_id: "45728", magic_set_id: MagicSet.find_by(code: "M13").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Magic 2014 Booster", mtgo_id: "49860", magic_set_id: MagicSet.find_by(code: "M14").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Magic 2015 Booster", mtgo_id: "53868", magic_set_id: MagicSet.find_by(code: "M15").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Masters Edition Booster", mtgo_id: "28159", magic_set_id: MagicSet.find_by(code: "MED").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Masters Edition II Booster", mtgo_id: "30839", magic_set_id: MagicSet.find_by(code: "ME2").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Masters Edition III Booster", mtgo_id: "33913", magic_set_id: MagicSet.find_by(code: "ME3").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Masters Edition IV Booster", mtgo_id: "39219", magic_set_id: MagicSet.find_by(code: "ME4").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Mercadian Masques Block Booster", mtgo_id: "43074", magic_set_id: MagicSet.find_by(code: "MM").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Mirage Booster", mtgo_id: "7470", magic_set_id: MagicSet.find_by(code: "MI").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Mirage Booster", mtgo_id: "7469", magic_set_id: MagicSet.find_by(code: "MI").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Mirage Booster", mtgo_id: "7468", magic_set_id: MagicSet.find_by(code: "MI").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Mirage Booster", mtgo_id: "7467", magic_set_id: MagicSet.find_by(code: "MI").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Mirage Booster", mtgo_id: "7466", magic_set_id: MagicSet.find_by(code: "MI").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Mirrodin Besieged Booster", mtgo_id: "39615", magic_set_id: MagicSet.find_by(code: "MBS").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Mirrodin Booster", mtgo_id: "20286", magic_set_id: MagicSet.find_by(code: "MRD").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Mirrodin Booster", mtgo_id: "20285", magic_set_id: MagicSet.find_by(code: "MRD").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Mirrodin Booster", mtgo_id: "20283", magic_set_id: MagicSet.find_by(code: "MRD").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Mirrodin Booster", mtgo_id: "20282", magic_set_id: MagicSet.find_by(code: "MRD").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Mirrodin Booster", mtgo_id: "20281", magic_set_id: MagicSet.find_by(code: "MRD").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Modern Masters Booster", mtgo_id: "49100", magic_set_id: MagicSet.find_by(code: "MMA").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Morningtide Booster", mtgo_id: "29260", magic_set_id: MagicSet.find_by(code: "MOR").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Morningtide Booster", mtgo_id: "29259", magic_set_id: MagicSet.find_by(code: "MOR").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Morningtide Booster", mtgo_id: "29251", magic_set_id: MagicSet.find_by(code: "MOR").id, disabled: true)
MagicCard.create(object_type: "pack", name: "New Phyrexia Booster", mtgo_id: "40460", magic_set_id: MagicSet.find_by(code: "NPH").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Ninth Edition Booster", mtgo_id: "22987", magic_set_id: MagicSet.find_by(code: "9ED").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Ninth Edition Booster", mtgo_id: "22986", magic_set_id: MagicSet.find_by(code: "9ED").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Ninth Edition Booster", mtgo_id: "22985", magic_set_id: MagicSet.find_by(code: "9ED").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Ninth Edition Booster", mtgo_id: "22984", magic_set_id: MagicSet.find_by(code: "9ED").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Ninth Edition Booster", mtgo_id: "22983", magic_set_id: MagicSet.find_by(code: "9ED").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Odyssey Booster", mtgo_id: "17059", magic_set_id: MagicSet.find_by(code: "OD").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Odyssey Booster", mtgo_id: "17058", magic_set_id: MagicSet.find_by(code: "OD").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Odyssey Booster", mtgo_id: "17057", magic_set_id: MagicSet.find_by(code: "OD").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Onslaught Booster", mtgo_id: "18352", magic_set_id: MagicSet.find_by(code: "ONS").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Onslaught Booster", mtgo_id: "18351", magic_set_id: MagicSet.find_by(code: "ONS").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Onslaught Booster", mtgo_id: "18349", magic_set_id: MagicSet.find_by(code: "ONS").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Onslaught Booster", mtgo_id: "18348", magic_set_id: MagicSet.find_by(code: "ONS").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Onslaught Booster", mtgo_id: "18347", magic_set_id: MagicSet.find_by(code: "ONS").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Planar Chaos Booster", mtgo_id: "26559", magic_set_id: MagicSet.find_by(code: "PLC").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Planar Chaos Booster", mtgo_id: "26558", magic_set_id: MagicSet.find_by(code: "PLC").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Planar Chaos Booster", mtgo_id: "26557", magic_set_id: MagicSet.find_by(code: "PLC").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Planeshift Booster", mtgo_id: "15331", magic_set_id: MagicSet.find_by(code: "PS").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Ravnica: City of Guilds Booster", mtgo_id: "23609", magic_set_id: MagicSet.find_by(code: "RAV").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Ravnica: City of Guilds Booster", mtgo_id: "23608", magic_set_id: MagicSet.find_by(code: "RAV").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Ravnica: City of Guilds Booster", mtgo_id: "23606", magic_set_id: MagicSet.find_by(code: "RAV").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Ravnica: City of Guilds Booster", mtgo_id: "23605", magic_set_id: MagicSet.find_by(code: "RAV").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Ravnica: City of Guilds Booster", mtgo_id: "23604", magic_set_id: MagicSet.find_by(code: "RAV").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Return to Ravnica Booster", mtgo_id: "46834", magic_set_id: MagicSet.find_by(code: "RTR").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Rise of the Eldrazi Booster", mtgo_id: "36830", magic_set_id: MagicSet.find_by(code: "ROE").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Saviors of Kamigawa Booster", mtgo_id: "22258", magic_set_id: MagicSet.find_by(code: "SOK").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Saviors of Kamigawa Booster", mtgo_id: "22257", magic_set_id: MagicSet.find_by(code: "SOK").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Saviors of Kamigawa Booster", mtgo_id: "22256", magic_set_id: MagicSet.find_by(code: "SOK").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Scars of Mirrodin Booster", mtgo_id: "38469", magic_set_id: MagicSet.find_by(code: "SOM").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Scourge Booster", mtgo_id: "18942", magic_set_id: MagicSet.find_by(code: "SCG").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Scourge Booster", mtgo_id: "18941", magic_set_id: MagicSet.find_by(code: "SCG").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Scourge Booster", mtgo_id: "18940", magic_set_id: MagicSet.find_by(code: "SCG").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Seventh Edition Booster", mtgo_id: "16041", magic_set_id: MagicSet.find_by(code: "7E").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Seventh Edition Booster", mtgo_id: "16040", magic_set_id: MagicSet.find_by(code: "7E").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Seventh Edition Booster", mtgo_id: "16039", magic_set_id: MagicSet.find_by(code: "7E").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Seventh Edition Booster", mtgo_id: "16038", magic_set_id: MagicSet.find_by(code: "7E").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Seventh Edition Booster", mtgo_id: "16037", magic_set_id: MagicSet.find_by(code: "7E").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Shadowmoor Booster", mtgo_id: "29901", magic_set_id: MagicSet.find_by(code: "SHM").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Shadowmoor Booster", mtgo_id: "29900", magic_set_id: MagicSet.find_by(code: "SHM").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Shadowmoor Booster", mtgo_id: "29899", magic_set_id: MagicSet.find_by(code: "SHM").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Shadowmoor Booster", mtgo_id: "29898", magic_set_id: MagicSet.find_by(code: "SHM").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Shadowmoor Booster", mtgo_id: "29897", magic_set_id: MagicSet.find_by(code: "SHM").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Shards of Alara Booster", mtgo_id: "31370", magic_set_id: MagicSet.find_by(code: "ALA").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Stronghold Booster", mtgo_id: "32127", magic_set_id: MagicSet.find_by(code: "ST").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Tempest Booster", mtgo_id: "31520", magic_set_id: MagicSet.find_by(code: "TE").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Tenth Edition Booster", mtgo_id: "27764", magic_set_id: MagicSet.find_by(code: "10E").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Tenth Edition Booster", mtgo_id: "27763", magic_set_id: MagicSet.find_by(code: "10E").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Tenth Edition Booster", mtgo_id: "27762", magic_set_id: MagicSet.find_by(code: "10E").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Tenth Edition Booster", mtgo_id: "27761", magic_set_id: MagicSet.find_by(code: "10E").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Tenth Edition Booster", mtgo_id: "23961", magic_set_id: MagicSet.find_by(code: "10E").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Theros Booster", mtgo_id: "50647", magic_set_id: MagicSet.find_by(code: "THS").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Time Spiral Booster", mtgo_id: "25956", magic_set_id: MagicSet.find_by(code: "TSP").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Time Spiral Booster", mtgo_id: "25955", magic_set_id: MagicSet.find_by(code: "TSP").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Time Spiral Booster", mtgo_id: "25954", magic_set_id: MagicSet.find_by(code: "TSP").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Time Spiral Booster", mtgo_id: "25953", magic_set_id: MagicSet.find_by(code: "TSP").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Time Spiral Booster", mtgo_id: "25952", magic_set_id: MagicSet.find_by(code: "TSP").id, disabled: true)
MagicCard.create(object_type: "pack", name: "Torment Booster", mtgo_id: "17351", magic_set_id: MagicSet.find_by(code: "TOR").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Urza's Destiny Booster", mtgo_id: "39670", magic_set_id: MagicSet.find_by(code: "UD").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Urza's Legacy Booster", mtgo_id: "36898", magic_set_id: MagicSet.find_by(code: "UL").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Urza's Saga Booster", mtgo_id: "36320", magic_set_id: MagicSet.find_by(code: "UZ").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Vintage Masters Booster", mtgo_id: "53247", magic_set_id: MagicSet.find_by(code: "VMA").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Visions Booster", mtgo_id: "23958", magic_set_id: MagicSet.find_by(code: "VI").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Weatherlight Booster", mtgo_id: "28808", magic_set_id: MagicSet.find_by(code: "WL").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Worldwake Booster", mtgo_id: "35841", magic_set_id: MagicSet.find_by(code: "WWK").id, disabled: false)
MagicCard.create(object_type: "pack", name: "Zendikar Booster", mtgo_id: "35036", magic_set_id: MagicSet.find_by(code: "ZEN").id, disabled: false)
