MagicCard.create(object_type: "planar", name: "Celestine Reef", mtgo_id: 44349, magic_set_id: MagicSet.find_by(code: "PRM").id, collector_number: "1010", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Celestine Reef", mtgo_id: 44348, magic_set_id: MagicSet.find_by(code: "PRM").id, collector_number: "1010", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Horizon Boughs", mtgo_id: 44347, magic_set_id: MagicSet.find_by(code: "PRM").id, collector_number: "1005", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Horizon Boughs", mtgo_id: 44346, magic_set_id: MagicSet.find_by(code: "PRM").id, collector_number: "1005", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Mirrored Depths", mtgo_id: 44345, magic_set_id: MagicSet.find_by(code: "PRM").id, collector_number: "1009", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Mirrored Depths", mtgo_id: 44344, magic_set_id: MagicSet.find_by(code: "PRM").id, collector_number: "1009", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Stairs to Infinity", mtgo_id: 44351, magic_set_id: MagicSet.find_by(code: "PRM").id, collector_number: "1007", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Stairs to Infinity", mtgo_id: 44350, magic_set_id: MagicSet.find_by(code: "PRM").id, collector_number: "1007", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Tazeem", mtgo_id: 44341, magic_set_id: MagicSet.find_by(code: "PRM").id, collector_number: "1008", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Tazeem", mtgo_id: 44340, magic_set_id: MagicSet.find_by(code: "PRM").id, collector_number: "1008", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Tember City", mtgo_id: 44343, magic_set_id: MagicSet.find_by(code: "PRM").id, collector_number: "1006", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Tember City", mtgo_id: 44342, magic_set_id: MagicSet.find_by(code: "PRM").id, collector_number: "1006", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Academy at Tolaria West", mtgo_id: 44513, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "1", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Academy at Tolaria West", mtgo_id: 44512, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "1", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Agyrem", mtgo_id: 44541, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "3", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Agyrem", mtgo_id: 44540, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "3", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Akoum", mtgo_id: 45091, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "9", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Akoum", mtgo_id: 45090, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "9", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Aretopolis", mtgo_id: 44961, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "10", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Aretopolis", mtgo_id: 44960, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "10", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Astral Arena", mtgo_id: 45009, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "11", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Astral Arena", mtgo_id: 45008, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "11", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Bant", mtgo_id: 44553, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "4", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Bant", mtgo_id: 44552, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "4", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Bloodhill Bastion", mtgo_id: 45021, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "12", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Bloodhill Bastion", mtgo_id: 45020, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "12", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Chaotic Æther", mtgo_id: 44997, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "1", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Chaotic Æther", mtgo_id: 44996, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "1", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Cliffside Market", mtgo_id: 44521, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "5", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Cliffside Market", mtgo_id: 44520, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "5", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Edge of Malacol", mtgo_id: 45011, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "13", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Edge of Malacol", mtgo_id: 45010, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "13", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Eloren Wilds", mtgo_id: 44567, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "7", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Eloren Wilds", mtgo_id: 44566, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "7", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Feeding Grounds", mtgo_id: 44503, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "9", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Feeding Grounds", mtgo_id: 44502, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "9", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Fields of Summer", mtgo_id: 44549, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "10", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Fields of Summer", mtgo_id: 44548, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "10", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Furnace Layer", mtgo_id: 45017, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "14", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Furnace Layer", mtgo_id: 45016, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "14", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Gavony", mtgo_id: 45027, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "15", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Gavony", mtgo_id: 45026, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "15", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Glen Elendra", mtgo_id: 44959, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "16", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Glen Elendra", mtgo_id: 44958, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "16", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Glimmervoid Basin", mtgo_id: 44507, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "12", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Glimmervoid Basin", mtgo_id: 44506, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "12", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Goldmeadow", mtgo_id: 44573, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "13", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Goldmeadow", mtgo_id: 44572, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "13", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Grand Ossuary", mtgo_id: 45041, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "17", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Grand Ossuary", mtgo_id: 45040, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "17", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Grixis", mtgo_id: 44511, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "15", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Grixis", mtgo_id: 44510, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "15", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Grove of the Dreampods", mtgo_id: 45025, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "18", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Grove of the Dreampods", mtgo_id: 45024, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "18", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Hedron Fields of Agadeem", mtgo_id: 44951, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "19", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Hedron Fields of Agadeem", mtgo_id: 44950, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "19", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Immersturm", mtgo_id: 44533, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "17", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Immersturm", mtgo_id: 44532, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "17", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Interplanar Tunnel", mtgo_id: 45035, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "2", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Interplanar Tunnel", mtgo_id: 45034, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "2", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Isle of Vesuva", mtgo_id: 44547, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "18", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Isle of Vesuva", mtgo_id: 44546, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "18", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Izzet Steam Maze", mtgo_id: 44501, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "19", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Izzet Steam Maze", mtgo_id: 44500, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "19", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Jund", mtgo_id: 44945, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "20", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Jund", mtgo_id: 44944, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "20", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Kessig", mtgo_id: 45019, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "21", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Kessig", mtgo_id: 45018, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "21", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Kharasha Foothills", mtgo_id: 45015, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "22", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Kharasha Foothills", mtgo_id: 45014, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "22", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Kilnspire District", mtgo_id: 44955, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "23", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Kilnspire District", mtgo_id: 44954, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "23", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Krosa", mtgo_id: 44555, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "20", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Krosa", mtgo_id: 44554, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "20", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Lair of the Ashen Idol", mtgo_id: 44963, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "24", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Lair of the Ashen Idol", mtgo_id: 44962, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "24", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Lethe Lake", mtgo_id: 44563, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "21", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Lethe Lake", mtgo_id: 44562, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "21", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Llanowar", mtgo_id: 44565, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "22", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Llanowar", mtgo_id: 44564, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "22", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Minamo", mtgo_id: 44523, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "24", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Minamo", mtgo_id: 44522, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "24", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Morphic Tide", mtgo_id: 45001, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "3", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Morphic Tide", mtgo_id: 45000, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "3", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Mount Keralia", mtgo_id: 45003, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "25", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Mount Keralia", mtgo_id: 45002, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "25", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Murasa", mtgo_id: 44515, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "25", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Murasa", mtgo_id: 44514, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "25", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Mutual Epiphany", mtgo_id: 45005, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "4", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Mutual Epiphany", mtgo_id: 45004, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "4", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Naar Isle", mtgo_id: 44509, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "26", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Naar Isle", mtgo_id: 44508, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "26", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Naya", mtgo_id: 44561, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "27", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Naya", mtgo_id: 44560, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "27", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Nephalia", mtgo_id: 45029, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "26", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Nephalia", mtgo_id: 45028, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "26", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Norn's Dominion", mtgo_id: 45023, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "27", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Norn's Dominion", mtgo_id: 45022, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "27", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Onakke Catacomb", mtgo_id: 44957, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "28", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Onakke Catacomb", mtgo_id: 44956, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "28", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Orochi Colony", mtgo_id: 44949, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "29", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Orochi Colony", mtgo_id: 44948, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "29", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Orzhova", mtgo_id: 44993, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "30", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Orzhova", mtgo_id: 44992, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "30", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Otaria", mtgo_id: 44545, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "28", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Otaria", mtgo_id: 44544, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "28", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Panopticon", mtgo_id: 44499, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "29", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Panopticon", mtgo_id: 44498, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "29", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Planewide Disaster", mtgo_id: 45031, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "5", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Planewide Disaster", mtgo_id: 45030, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "5", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Pools of Becoming", mtgo_id: 44527, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "30", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Pools of Becoming", mtgo_id: 44526, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "30", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Prahv", mtgo_id: 45037, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "31", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Prahv", mtgo_id: 45036, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "31", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Quicksilver Sea", mtgo_id: 44967, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "32", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Quicksilver Sea", mtgo_id: 44966, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "32", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Raven's Run", mtgo_id: 44519, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "31", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Raven's Run", mtgo_id: 44518, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "31", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Reality Shaping", mtgo_id: 44995, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "6", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Reality Shaping", mtgo_id: 44994, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "6", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Sanctum of Serra", mtgo_id: 44525, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "32", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Sanctum of Serra", mtgo_id: 44524, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "32", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Sea of Sand", mtgo_id: 44571, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "33", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Sea of Sand", mtgo_id: 44570, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "33", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Selesnya Loft Gardens", mtgo_id: 44947, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "33", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Selesnya Loft Gardens", mtgo_id: 44946, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "33", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Shiv", mtgo_id: 44537, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "34", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Shiv", mtgo_id: 44536, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "34", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Skybreen", mtgo_id: 44557, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "35", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Skybreen", mtgo_id: 44556, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "35", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Sokenzan", mtgo_id: 44517, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "36", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Sokenzan", mtgo_id: 44516, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "36", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Spatial Merging", mtgo_id: 45033, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "7", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Spatial Merging", mtgo_id: 45032, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "7", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Stensia", mtgo_id: 45043, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "34", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Stensia", mtgo_id: 45042, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "34", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Stronghold Furnace", mtgo_id: 44497, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "37", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Stronghold Furnace", mtgo_id: 44496, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "37", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Takenuma", mtgo_id: 45093, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "35", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Takenuma", mtgo_id: 45092, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "35", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Talon Gates", mtgo_id: 45007, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "36", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Talon Gates", mtgo_id: 45006, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "36", foil: FALSE)
MagicCard.create(object_type: "planar", name: "The Æther Flues", mtgo_id: 44551, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "2", foil: TRUE)
MagicCard.create(object_type: "planar", name: "The Æther Flues", mtgo_id: 44550, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "2", foil: FALSE)
MagicCard.create(object_type: "planar", name: "The Dark Barony", mtgo_id: 44531, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "6", foil: TRUE)
MagicCard.create(object_type: "planar", name: "The Dark Barony", mtgo_id: 44530, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "6", foil: FALSE)
MagicCard.create(object_type: "planar", name: "The Eon Fog", mtgo_id: 44543, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "8", foil: TRUE)
MagicCard.create(object_type: "planar", name: "The Eon Fog", mtgo_id: 44542, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "8", foil: FALSE)
MagicCard.create(object_type: "planar", name: "The Fourth Sphere", mtgo_id: 44559, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "11", foil: TRUE)
MagicCard.create(object_type: "planar", name: "The Fourth Sphere", mtgo_id: 44558, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "11", foil: FALSE)
MagicCard.create(object_type: "planar", name: "The Great Forest", mtgo_id: 44539, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "14", foil: TRUE)
MagicCard.create(object_type: "planar", name: "The Great Forest", mtgo_id: 44538, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "14", foil: FALSE)
MagicCard.create(object_type: "planar", name: "The Hippodrome", mtgo_id: 44505, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "16", foil: TRUE)
MagicCard.create(object_type: "planar", name: "The Hippodrome", mtgo_id: 44504, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "16", foil: FALSE)
MagicCard.create(object_type: "planar", name: "The Maelstrom", mtgo_id: 44495, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "23", foil: TRUE)
MagicCard.create(object_type: "planar", name: "The Maelstrom", mtgo_id: 44494, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "23", foil: FALSE)
MagicCard.create(object_type: "planar", name: "The Zephyr Maze", mtgo_id: 45013, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "40", foil: TRUE)
MagicCard.create(object_type: "planar", name: "The Zephyr Maze", mtgo_id: 45012, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "40", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Time Distortion", mtgo_id: 45045, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "8", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Time Distortion", mtgo_id: 45044, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "8", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Trail of the Mage-Rings", mtgo_id: 44953, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "37", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Trail of the Mage-Rings", mtgo_id: 44952, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "37", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Truga Jungle", mtgo_id: 45039, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "38", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Truga Jungle", mtgo_id: 45038, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "38", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Turri Island", mtgo_id: 44535, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "38", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Turri Island", mtgo_id: 44534, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "38", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Undercity Reaches", mtgo_id: 44569, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "39", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Undercity Reaches", mtgo_id: 44568, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "39", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Velis Vel", mtgo_id: 44529, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "40", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Velis Vel", mtgo_id: 44528, magic_set_id: MagicSet.find_by(code: "PC1").id, collector_number: "40", foil: FALSE)
MagicCard.create(object_type: "planar", name: "Windriddle Palaces", mtgo_id: 44999, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "39", foil: TRUE)
MagicCard.create(object_type: "planar", name: "Windriddle Palaces", mtgo_id: 44998, magic_set_id: MagicSet.find_by(code: "PC2").id, collector_number: "39", foil: FALSE)
