MagicSet.create(name: "Duel Decks: Elves vs Goblins", code: "EVG", magic_block_id: MagicBlock.find_by(name: "Duel Decks" ).id)
MagicSet.create(name: "Duel Decks: Jace vs Chandra", code: "DD2", magic_block_id: MagicBlock.find_by(name: "Duel Decks" ).id)
MagicSet.create(name: "Duel Decks: Divine vs Demonic", code: "DDC", magic_block_id: MagicBlock.find_by(name: "Duel Decks" ).id)
MagicSet.create(name: "Duel Decks: Garruk vs Liliana", code: "DDD", magic_block_id: MagicBlock.find_by(name: "Duel Decks" ).id)
MagicSet.create(name: "Duel Decks: Phyrexia vs The Coalition", code: "DDE", magic_block_id: MagicBlock.find_by(name: "Duel Decks" ).id)
MagicSet.create(name: "Duel Decks: Elspeth vs Tezzeret", code: "DDF", magic_block_id: MagicBlock.find_by(name: "Duel Decks" ).id)
MagicSet.create(name: "Duel Decks: Knights vs Dragons", code: "DDG", magic_block_id: MagicBlock.find_by(name: "Duel Decks" ).id)
MagicSet.create(name: "Duel Decks: Mirrodin Pure vs New Phyrexia", code: "TD2", magic_block_id: MagicBlock.find_by(name: "Duel Decks" ).id)
MagicSet.create(name: "Duel Decks: Ajani vs Nicol Bolas", code: "DDH", magic_block_id: MagicBlock.find_by(name: "Duel Decks" ).id)
MagicSet.create(name: "Duel Decks: Venser vs Koth", code: "DDI", magic_block_id: MagicBlock.find_by(name: "Duel Decks" ).id)
MagicSet.create(name: "Duel Decks: Izzet vs Golgari", code: "DDJ", magic_block_id: MagicBlock.find_by(name: "Duel Decks" ).id)
MagicSet.create(name: "Duel Decks: Sorin vs Tibalt", code: "DDK", magic_block_id: MagicBlock.find_by(name: "Duel Decks" ).id)
MagicSet.create(name: "Duel Decks: Jace vs. Vraska", code: "DDM", magic_block_id: MagicBlock.find_by(name: "Duel Decks" ).id)
MagicSet.create(name: "Duel Decks: Heroes vs. Monsters", code: "DDL", magic_block_id: MagicBlock.find_by(name: "Duel Decks" ).id)
MagicSet.create(name: "From the Vault: Dragons", code: "DRB", magic_block_id: MagicBlock.find_by(name: "From the Vault" ).id)
MagicSet.create(name: "From the Vault: Exiled", code: "V09", magic_block_id: MagicBlock.find_by(name: "From the Vault" ).id)
MagicSet.create(name: "From the Vault: Relics", code: "V10", magic_block_id: MagicBlock.find_by(name: "From the Vault" ).id)
MagicSet.create(name: "From the Vault: Legends", code: "V11", magic_block_id: MagicBlock.find_by(name: "From the Vault" ).id)
MagicSet.create(name: "From the Vault: Realms", code: "V12", magic_block_id: MagicBlock.find_by(name: "From the Vault" ).id)
MagicSet.create(name: "From the Vault: Twenty", code: "V13", magic_block_id: MagicBlock.find_by(name: "From the Vault" ).id)
MagicSet.create(name: "From the Vault: Annihilation", code: "V14", magic_block_id: MagicBlock.find_by(name: "From the Vault" ).id)
MagicSet.create(name: "Slivers", code: "H09", magic_block_id: MagicBlock.find_by(name: "Premium Deck Series" ).id)
MagicSet.create(name: "Fire and Lightning", code: "PD2", magic_block_id: MagicBlock.find_by(name: "Premium Deck Series" ).id)
MagicSet.create(name: "Graveborn", code: "PD3", magic_block_id: MagicBlock.find_by(name: "Premium Deck Series" ).id)
MagicSet.create(name: "Planechase (2009 Edition)", code: "PC1", magic_block_id: MagicBlock.find_by(name: "Planechase" ).id)
MagicSet.create(name: "Planechase (2012 Edition)", code: "PC2", magic_block_id: MagicBlock.find_by(name: "Planechase" ).id)
MagicSet.create(name: "Commander (2011 Edition)", code: "CMD", magic_block_id: MagicBlock.find_by(name: "Commander" ).id)
MagicSet.create(name: "Commander (2013 Edition)", code: "C13", magic_block_id: MagicBlock.find_by(name: "Commander" ).id)
MagicSet.create(name: "Commander (2014 Edition)", code: "C14", magic_block_id: MagicBlock.find_by(name: "Commander" ).id)
MagicSet.create(name: "Theme Deck Set", code: "TD0", magic_block_id: MagicBlock.find_by(name: "Other" ).id)
MagicSet.create(name: "Promotional", code: "PRM", magic_block_id: MagicBlock.find_by(name: "Other" ).id)
MagicSet.create(name: "Vanguard", code: "VAN", magic_block_id: MagicBlock.find_by(name: "Other" ).id)
MagicSet.create(name: "Masters Edition", code: "MED", magic_block_id: MagicBlock.find_by(name: "Masters Editions" ).id)
MagicSet.create(name: "Masters Edition II", code: "ME2", magic_block_id: MagicBlock.find_by(name: "Masters Editions" ).id)
MagicSet.create(name: "Masters Edition III", code: "ME3", magic_block_id: MagicBlock.find_by(name: "Masters Editions" ).id)
MagicSet.create(name: "Masters Edition IV", code: "ME4", magic_block_id: MagicBlock.find_by(name: "Masters Editions" ).id)
MagicSet.create(name: "Modern Masters", code: "MMA", magic_block_id: MagicBlock.find_by(name: "Masters Editions" ).id) 
MagicSet.create(name: "Modern Masters 2015", code: "MM2", magic_block_id: MagicBlock.find_by(name: "Masters Editions" ).id)
MagicSet.create(name: "Vintage Masters", code: "VMA", magic_block_id: MagicBlock.find_by(name: "Masters Editions" ).id)
MagicSet.create(name: "Seventh Edition", code: "7E", magic_block_id: MagicBlock.find_by(name: "Core Sets" ).id)
MagicSet.create(name: "Eighth Edition", code: "8ED", magic_block_id: MagicBlock.find_by(name: "Core Sets" ).id)
MagicSet.create(name: "Ninth Edition", code: "9ED", magic_block_id: MagicBlock.find_by(name: "Core Sets" ).id)
MagicSet.create(name: "Tenth Edition", code: "10E", magic_block_id: MagicBlock.find_by(name: "Core Sets" ).id)
MagicSet.create(name: "Magic 2010", code: "M10", magic_block_id: MagicBlock.find_by(name: "Core Sets" ).id)
MagicSet.create(name: "Magic 2011", code: "M11", magic_block_id: MagicBlock.find_by(name: "Core Sets" ).id)
MagicSet.create(name: "Magic 2012", code: "M12", magic_block_id: MagicBlock.find_by(name: "Core Sets" ).id)
MagicSet.create(name: "Magic 2013", code: "M13", magic_block_id: MagicBlock.find_by(name: "Core Sets" ).id)
MagicSet.create(name: "Magic 2014", code: "M14", magic_block_id: MagicBlock.find_by(name: "Core Sets" ).id)
MagicSet.create(name: "Magic 2015", code: "M15", magic_block_id: MagicBlock.find_by(name: "Core Sets" ).id)
MagicSet.create(name: "Mirage", code: "MI", magic_block_id: MagicBlock.find_by(name: "Mirage Block" ).id)
MagicSet.create(name: "Visions", code: "VI", magic_block_id: MagicBlock.find_by(name: "Mirage Block" ).id)
MagicSet.create(name: "Weatherlight", code: "WL", magic_block_id: MagicBlock.find_by(name: "Mirage Block" ).id)
MagicSet.create(name: "Tempest", code: "TE", magic_block_id: MagicBlock.find_by(name: "Tempest Block" ).id)
MagicSet.create(name: "Stronghold", code: "ST", magic_block_id: MagicBlock.find_by(name: "Tempest Block" ).id)
MagicSet.create(name: "Exodus", code: "EX", magic_block_id: MagicBlock.find_by(name: "Tempest Block" ).id)
MagicSet.create(name: "Urza's Saga", code: "UZ", magic_block_id: MagicBlock.find_by(name: "Urza Block" ).id)
MagicSet.create(name: "Urza's Legacy", code: "UL", magic_block_id: MagicBlock.find_by(name: "Urza Block" ).id)
MagicSet.create(name: "Urza's Destiny", code: "UD", magic_block_id: MagicBlock.find_by(name: "Urza Block" ).id)
MagicSet.create(name: "Mercadian Masques", code: "MM", magic_block_id: MagicBlock.find_by(name: "Masques Block" ).id)
MagicSet.create(name: "Nemesis", code: "NE", magic_block_id: MagicBlock.find_by(name: "Masques Block" ).id)
MagicSet.create(name: "Prophecy", code: "PR", magic_block_id: MagicBlock.find_by(name: "Masques Block" ).id)
MagicSet.create(name: "Invasion", code: "IN", magic_block_id: MagicBlock.find_by(name: "Invasion Block" ).id)
MagicSet.create(name: "Planeshift", code: "PS", magic_block_id: MagicBlock.find_by(name: "Invasion Block" ).id)
MagicSet.create(name: "Apocalypse", code: "AP", magic_block_id: MagicBlock.find_by(name: "Invasion Block" ).id)
MagicSet.create(name: "Odyssey", code: "OD", magic_block_id: MagicBlock.find_by(name: "Odyssey Block" ).id)
MagicSet.create(name: "Torment", code: "TOR", magic_block_id: MagicBlock.find_by(name: "Odyssey Block" ).id)
MagicSet.create(name: "Judgment", code: "JUD", magic_block_id: MagicBlock.find_by(name: "Odyssey Block" ).id)
MagicSet.create(name: "Onslaught", code: "ONS", magic_block_id: MagicBlock.find_by(name: "Onslaught Block" ).id)
MagicSet.create(name: "Legions", code: "LGN", magic_block_id: MagicBlock.find_by(name: "Onslaught Block" ).id)
MagicSet.create(name: "Scourge", code: "SCG", magic_block_id: MagicBlock.find_by(name: "Onslaught Block" ).id)
MagicSet.create(name: "Mirrodin", code: "MRD", magic_block_id: MagicBlock.find_by(name: "Mirrodin Block" ).id)
MagicSet.create(name: "Darksteel", code: "DST", magic_block_id: MagicBlock.find_by(name: "Mirrodin Block" ).id)
MagicSet.create(name: "Fifth Dawn", code: "5DN", magic_block_id: MagicBlock.find_by(name: "Mirrodin Block" ).id)
MagicSet.create(name: "Champions of Kamigawa", code: "CHK", magic_block_id: MagicBlock.find_by(name: "Kamigawa Block" ).id)
MagicSet.create(name: "Betrayers of Kamigawa", code: "BOK", magic_block_id: MagicBlock.find_by(name: "Kamigawa Block" ).id)
MagicSet.create(name: "Saviors of Kamigawa", code: "SOK", magic_block_id: MagicBlock.find_by(name: "Kamigawa Block" ).id)
MagicSet.create(name: "Ravnica: City of Guilds", code: "RAV", magic_block_id: MagicBlock.find_by(name: "Ravnica Block" ).id)
MagicSet.create(name: "Guildpact", code: "GPT", magic_block_id: MagicBlock.find_by(name: "Ravnica Block" ).id)
MagicSet.create(name: "Dissension", code: "DIS", magic_block_id: MagicBlock.find_by(name: "Ravnica Block" ).id)
MagicSet.create(name: "Coldsnap", code: "CSP", magic_block_id: MagicBlock.find_by(name: "Ice Age Block" ).id)
MagicSet.create(name: "Time Spiral", code: "TSP", magic_block_id: MagicBlock.find_by(name: "Time Spiral Block" ).id)
MagicSet.create(name: "Timeshifted", code: "TSB", magic_block_id: MagicBlock.find_by(name: "Time Spiral Block" ).id)
MagicSet.create(name: "Planar Chaos", code: "PLC", magic_block_id: MagicBlock.find_by(name: "Time Spiral Block" ).id)
MagicSet.create(name: "Future Sight", code: "FUT", magic_block_id: MagicBlock.find_by(name: "Time Spiral Block" ).id)
MagicSet.create(name: "Lorwyn", code: "LRW", magic_block_id: MagicBlock.find_by(name: "Lorwyn-Shadowmoor Block" ).id)
MagicSet.create(name: "Morningtide", code: "MOR", magic_block_id: MagicBlock.find_by(name: "Lorwyn-Shadowmoor Block" ).id)
MagicSet.create(name: "Shadowmoor", code: "SHM", magic_block_id: MagicBlock.find_by(name: "Lorwyn-Shadowmoor Block" ).id)
MagicSet.create(name: "Eventide", code: "EVE", magic_block_id: MagicBlock.find_by(name: "Lorwyn-Shadowmoor Block" ).id)
MagicSet.create(name: "Shards of Alara", code: "ALA", magic_block_id: MagicBlock.find_by(name: "Shards of Alara Block" ).id)
MagicSet.create(name: "Conflux", code: "_CON", magic_block_id: MagicBlock.find_by(name: "Shards of Alara Block" ).id)
MagicSet.create(name: "Alara Reborn", code: "ARB", magic_block_id: MagicBlock.find_by(name: "Shards of Alara Block" ).id)
MagicSet.create(name: "Zendikar", code: "ZEN", magic_block_id: MagicBlock.find_by(name: "Zendikar Block" ).id)
MagicSet.create(name: "Worldwake", code: "WWK", magic_block_id: MagicBlock.find_by(name: "Zendikar Block" ).id)
MagicSet.create(name: "Rise of the Eldrazi", code: "ROE", magic_block_id: MagicBlock.find_by(name: "Zendikar Block" ).id)
MagicSet.create(name: "Scars of Mirrodin", code: "SOM", magic_block_id: MagicBlock.find_by(name: "Scars of Mirrodin Block" ).id)
MagicSet.create(name: "Mirrodin Besieged", code: "MBS", magic_block_id: MagicBlock.find_by(name: "Scars of Mirrodin Block" ).id)
MagicSet.create(name: "New Phyrexia", code: "NPH", magic_block_id: MagicBlock.find_by(name: "Scars of Mirrodin Block" ).id)
MagicSet.create(name: "Innistrad", code: "ISD", magic_block_id: MagicBlock.find_by(name: "Innistrad Block" ).id)
MagicSet.create(name: "Dark Ascension", code: "DKA", magic_block_id: MagicBlock.find_by(name: "Innistrad Block" ).id)
MagicSet.create(name: "Avacyn Restored", code: "AVR", magic_block_id: MagicBlock.find_by(name: "Innistrad Block" ).id)
MagicSet.create(name: "Return to Ravnica", code: "RTR", magic_block_id: MagicBlock.find_by(name: "Return to Ravnica Block" ).id)
MagicSet.create(name: "Gatecrash", code: "GTC", magic_block_id: MagicBlock.find_by(name: "Return to Ravnica Block" ).id)
MagicSet.create(name: "Dragon's Maze", code: "DGM", magic_block_id: MagicBlock.find_by(name: "Return to Ravnica Block" ).id)
MagicSet.create(name: "Theros", code: "THS", magic_block_id: MagicBlock.find_by(name: "Theros Block" ).id)
MagicSet.create(name: "Born of the Gods", code: "BNG", magic_block_id: MagicBlock.find_by(name: "Theros Block" ).id)
MagicSet.create(name: "Journey into Nyx", code: "JOU", magic_block_id: MagicBlock.find_by(name: "Theros Block" ).id)
MagicSet.create(name: "Khans of Tarkir", code: "KTK", magic_block_id: MagicBlock.find_by(name: "Khans of Tarkir Block" ).id)
MagicSet.create(name: "Fate Reforged", code: "FRF", magic_block_id: MagicBlock.find_by(name: "Khans of Tarkir Block" ).id)
MagicSet.create(name: "Dragons of Tarkir", code: "DTK", magic_block_id: MagicBlock.find_by(name: "Khans of Tarkir Block" ).id)
MagicSet.create(name: "Modern Masters 2015", code: "MM2", magic_block_id: MagicBlock.find_by(name: "" ).id)

