MagicCard.create(object_type: "card", name: "Azorius Chancery", mtgo_id: 57475, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "235", foil:TRUE)
MagicCard.create(object_type: "card", name: "Azorius Chancery", mtgo_id: 57474, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "235", foil:FALSE)
MagicCard.create(object_type: "card", name: "Blinkmoth Nexus", mtgo_id: 57351, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "236", foil:TRUE)
MagicCard.create(object_type: "card", name: "Blinkmoth Nexus", mtgo_id: 57350, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "236", foil:FALSE)
MagicCard.create(object_type: "card", name: "Boros Garrison", mtgo_id: 57427, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "237", foil:TRUE)
MagicCard.create(object_type: "card", name: "Boros Garrison", mtgo_id: 57426, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "237", foil:FALSE)
MagicCard.create(object_type: "card", name: "Darksteel Citadel", mtgo_id: 57389, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "238", foil:TRUE)
MagicCard.create(object_type: "card", name: "Darksteel Citadel", mtgo_id: 57388, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "238", foil:FALSE)
MagicCard.create(object_type: "card", name: "Dimir Aqueduct", mtgo_id: 57431, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "239", foil:TRUE)
MagicCard.create(object_type: "card", name: "Dimir Aqueduct", mtgo_id: 57430, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "239", foil:FALSE)
MagicCard.create(object_type: "card", name: "Eldrazi Temple", mtgo_id: 57219, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "240", foil:TRUE)
MagicCard.create(object_type: "card", name: "Eldrazi Temple", mtgo_id: 57218, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "240", foil:FALSE)
MagicCard.create(object_type: "card", name: "Evolving Wilds", mtgo_id: 57189, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "241", foil:TRUE)
MagicCard.create(object_type: "card", name: "Evolving Wilds", mtgo_id: 57188, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "241", foil:FALSE)
MagicCard.create(object_type: "card", name: "Eye of Ugin", mtgo_id: 57165, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "242", foil:TRUE)
MagicCard.create(object_type: "card", name: "Eye of Ugin", mtgo_id: 57164, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "242", foil:FALSE)
MagicCard.create(object_type: "card", name: "Golgari Rot Farm", mtgo_id: 57435, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "243", foil:TRUE)
MagicCard.create(object_type: "card", name: "Golgari Rot Farm", mtgo_id: 57434, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "243", foil:FALSE)
MagicCard.create(object_type: "card", name: "Gruul Turf", mtgo_id: 57469, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "244", foil:TRUE)
MagicCard.create(object_type: "card", name: "Gruul Turf", mtgo_id: 57468, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "244", foil:FALSE)
MagicCard.create(object_type: "card", name: "Izzet Boilerworks", mtgo_id: 57467, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "245", foil:TRUE)
MagicCard.create(object_type: "card", name: "Izzet Boilerworks", mtgo_id: 57466, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "245", foil:FALSE)
MagicCard.create(object_type: "card", name: "Orzhov Basilica", mtgo_id: 57457, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "246", foil:TRUE)
MagicCard.create(object_type: "card", name: "Orzhov Basilica", mtgo_id: 57456, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "246", foil:FALSE)
MagicCard.create(object_type: "card", name: "Rakdos Carnarium", mtgo_id: 57473, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "247", foil:TRUE)
MagicCard.create(object_type: "card", name: "Rakdos Carnarium", mtgo_id: 57472, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "247", foil:FALSE)
MagicCard.create(object_type: "card", name: "Selesnya Sanctuary", mtgo_id: 57437, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "248", foil:TRUE)
MagicCard.create(object_type: "card", name: "Selesnya Sanctuary", mtgo_id: 57436, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "248", foil:FALSE)
MagicCard.create(object_type: "card", name: "Simic Growth Chamber", mtgo_id: 57477, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "249", foil:TRUE)
MagicCard.create(object_type: "card", name: "Simic Growth Chamber", mtgo_id: 57476, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "249", foil:FALSE)
MagicCard.create(object_type: "card", name: "Everflowing Chalice", mtgo_id: 57167, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "212", foil:TRUE)
MagicCard.create(object_type: "card", name: "Everflowing Chalice", mtgo_id: 57166, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "212", foil:FALSE)
MagicCard.create(object_type: "card", name: "Mox Opal", mtgo_id: 57259, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "223", foil:TRUE)
MagicCard.create(object_type: "card", name: "Mox Opal", mtgo_id: 57258, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "223", foil:FALSE)
MagicCard.create(object_type: "card", name: "Copper Carapace", mtgo_id: 57293, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "205", foil:TRUE)
MagicCard.create(object_type: "card", name: "Copper Carapace", mtgo_id: 57292, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "205", foil:FALSE)
MagicCard.create(object_type: "card", name: "Darksteel Axe", mtgo_id: 57265, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "208", foil:TRUE)
MagicCard.create(object_type: "card", name: "Darksteel Axe", mtgo_id: 57264, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "208", foil:FALSE)
MagicCard.create(object_type: "card", name: "Expedition Map", mtgo_id: 57179, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "213", foil:TRUE)
MagicCard.create(object_type: "card", name: "Expedition Map", mtgo_id: 57178, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "213", foil:FALSE)
MagicCard.create(object_type: "card", name: "Flayer Husk", mtgo_id: 57297, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "214", foil:TRUE)
MagicCard.create(object_type: "card", name: "Flayer Husk", mtgo_id: 57296, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "214", foil:FALSE)
MagicCard.create(object_type: "card", name: "Wayfarer's Bauble", mtgo_id: 57391, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "234", foil:TRUE)
MagicCard.create(object_type: "card", name: "Wayfarer's Bauble", mtgo_id: 57390, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "234", foil:FALSE)
MagicCard.create(object_type: "card", name: "Court Homunculus", mtgo_id: 57119, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "13", foil:TRUE)
MagicCard.create(object_type: "card", name: "Court Homunculus", mtgo_id: 57118, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "13", foil:FALSE)
MagicCard.create(object_type: "card", name: "Dispatch", mtgo_id: 57325, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "15", foil:TRUE)
MagicCard.create(object_type: "card", name: "Dispatch", mtgo_id: 57324, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "15", foil:FALSE)
MagicCard.create(object_type: "card", name: "Kor Duelist", mtgo_id: 57147, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "22", foil:TRUE)
MagicCard.create(object_type: "card", name: "Kor Duelist", mtgo_id: 57146, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "22", foil:FALSE)
MagicCard.create(object_type: "card", name: "Sunlance", mtgo_id: 57007, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "34", foil:TRUE)
MagicCard.create(object_type: "card", name: "Sunlance", mtgo_id: 57006, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "34", foil:FALSE)
MagicCard.create(object_type: "card", name: "Vapor Snag", mtgo_id: 57323, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "66", foil:TRUE)
MagicCard.create(object_type: "card", name: "Vapor Snag", mtgo_id: 57322, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "66", foil:FALSE)
MagicCard.create(object_type: "card", name: "Surgical Extraction", mtgo_id: 57339, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "99", foil:TRUE)
MagicCard.create(object_type: "card", name: "Surgical Extraction", mtgo_id: 57338, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "99", foil:FALSE)
MagicCard.create(object_type: "card", name: "Bone Splinters", mtgo_id: 57107, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "73", foil:TRUE)
MagicCard.create(object_type: "card", name: "Bone Splinters", mtgo_id: 57106, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "73", foil:FALSE)
MagicCard.create(object_type: "card", name: "Deathmark", mtgo_id: 57143, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "77", foil:TRUE)
MagicCard.create(object_type: "card", name: "Deathmark", mtgo_id: 57142, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "77", foil:FALSE)
MagicCard.create(object_type: "card", name: "Plagued Rusalka", mtgo_id: 57471, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "89", foil:TRUE)
MagicCard.create(object_type: "card", name: "Plagued Rusalka", mtgo_id: 57470, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "89", foil:FALSE)
MagicCard.create(object_type: "card", name: "Vampire Lacerator", mtgo_id: 57161, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "101", foil:TRUE)
MagicCard.create(object_type: "card", name: "Vampire Lacerator", mtgo_id: 57160, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "101", foil:FALSE)
MagicCard.create(object_type: "card", name: "Gut Shot", mtgo_id: 57329, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "117", foil:TRUE)
MagicCard.create(object_type: "card", name: "Gut Shot", mtgo_id: 57328, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "117", foil:FALSE)
MagicCard.create(object_type: "card", name: "Brute Force", mtgo_id: 57009, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "108", foil:TRUE)
MagicCard.create(object_type: "card", name: "Brute Force", mtgo_id: 57008, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "108", foil:FALSE)
MagicCard.create(object_type: "card", name: "Burst Lightning", mtgo_id: 57149, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "109", foil:TRUE)
MagicCard.create(object_type: "card", name: "Burst Lightning", mtgo_id: 57148, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "109", foil:FALSE)
MagicCard.create(object_type: "card", name: "Goblin Fireslinger", mtgo_id: 57337, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "114", foil:TRUE)
MagicCard.create(object_type: "card", name: "Goblin Fireslinger", mtgo_id: 57336, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "114", foil:FALSE)
MagicCard.create(object_type: "card", name: "Lightning Bolt", mtgo_id: 57141, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "122", foil:TRUE)
MagicCard.create(object_type: "card", name: "Lightning Bolt", mtgo_id: 57140, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "122", foil:FALSE)
MagicCard.create(object_type: "card", name: "Spikeshot Elder", mtgo_id: 57267, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "127", foil:TRUE)
MagicCard.create(object_type: "card", name: "Spikeshot Elder", mtgo_id: 57266, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "127", foil:FALSE)
MagicCard.create(object_type: "card", name: "Mutagenic Growth", mtgo_id: 57335, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "149", foil:TRUE)
MagicCard.create(object_type: "card", name: "Mutagenic Growth", mtgo_id: 57334, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "149", foil:FALSE)
MagicCard.create(object_type: "card", name: "Commune with Nature", mtgo_id: 57017, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "142", foil:TRUE)
MagicCard.create(object_type: "card", name: "Commune with Nature", mtgo_id: 57016, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "142", foil:FALSE)
MagicCard.create(object_type: "card", name: "Noble Hierarch", mtgo_id: 57113, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "151", foil:TRUE)
MagicCard.create(object_type: "card", name: "Noble Hierarch", mtgo_id: 57112, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "151", foil:FALSE)
MagicCard.create(object_type: "card", name: "Scute Mob", mtgo_id: 57153, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "161", foil:TRUE)
MagicCard.create(object_type: "card", name: "Scute Mob", mtgo_id: 57152, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "161", foil:FALSE)
MagicCard.create(object_type: "card", name: "Simic Initiate", mtgo_id: 57489, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "162", foil:TRUE)
MagicCard.create(object_type: "card", name: "Simic Initiate", mtgo_id: 57488, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "162", foil:FALSE)
MagicCard.create(object_type: "card", name: "Tukatongue Thallid", mtgo_id: 57127, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "167", foil:TRUE)
MagicCard.create(object_type: "card", name: "Tukatongue Thallid", mtgo_id: 57126, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "167", foil:FALSE)
MagicCard.create(object_type: "card", name: "Vines of Vastwood", mtgo_id: 57151, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "168", foil:TRUE)
MagicCard.create(object_type: "card", name: "Vines of Vastwood", mtgo_id: 57150, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "168", foil:FALSE)
MagicCard.create(object_type: "card", name: "Cranial Plating", mtgo_id: 57393, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "206", foil:TRUE)
MagicCard.create(object_type: "card", name: "Cranial Plating", mtgo_id: 57392, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "206", foil:FALSE)
MagicCard.create(object_type: "card", name: "Culling Dais", mtgo_id: 57245, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "207", foil:TRUE)
MagicCard.create(object_type: "card", name: "Culling Dais", mtgo_id: 57244, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "207", foil:FALSE)
MagicCard.create(object_type: "card", name: "Glint Hawk Idol", mtgo_id: 57241, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "216", foil:TRUE)
MagicCard.create(object_type: "card", name: "Glint Hawk Idol", mtgo_id: 57240, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "216", foil:FALSE)
MagicCard.create(object_type: "card", name: "Gust-Skimmer", mtgo_id: 57287, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "217", foil:TRUE)
MagicCard.create(object_type: "card", name: "Gust-Skimmer", mtgo_id: 57286, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "217", foil:FALSE)
MagicCard.create(object_type: "card", name: "Kitesail", mtgo_id: 57175, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "218", foil:TRUE)
MagicCard.create(object_type: "card", name: "Kitesail", mtgo_id: 57174, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "218", foil:FALSE)
MagicCard.create(object_type: "card", name: "Mortarpod", mtgo_id: 57285, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "222", foil:TRUE)
MagicCard.create(object_type: "card", name: "Mortarpod", mtgo_id: 57284, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "222", foil:FALSE)
MagicCard.create(object_type: "card", name: "Runed Servitor", mtgo_id: 57209, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "226", foil:TRUE)
MagicCard.create(object_type: "card", name: "Runed Servitor", mtgo_id: 57208, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "226", foil:FALSE)
MagicCard.create(object_type: "card", name: "Spellskite", mtgo_id: 57319, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "230", foil:TRUE)
MagicCard.create(object_type: "card", name: "Spellskite", mtgo_id: 57318, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "230", foil:FALSE)
MagicCard.create(object_type: "card", name: "Sphere of the Suns", mtgo_id: 57289, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "231", foil:TRUE)
MagicCard.create(object_type: "card", name: "Sphere of the Suns", mtgo_id: 57288, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "231", foil:FALSE)
MagicCard.create(object_type: "card", name: "Apostle's Blessing", mtgo_id: 57307, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "8", foil:TRUE)
MagicCard.create(object_type: "card", name: "Apostle's Blessing", mtgo_id: 57306, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "8", foil:FALSE)
MagicCard.create(object_type: "card", name: "Celestial Purge", mtgo_id: 57123, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "11", foil:TRUE)
MagicCard.create(object_type: "card", name: "Celestial Purge", mtgo_id: 57122, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "11", foil:FALSE)
MagicCard.create(object_type: "card", name: "Kami of Ancient Law", mtgo_id: 57405, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "21", foil:TRUE)
MagicCard.create(object_type: "card", name: "Kami of Ancient Law", mtgo_id: 57404, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "21", foil:FALSE)
MagicCard.create(object_type: "card", name: "Mighty Leap", mtgo_id: 57239, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "24", foil:TRUE)
MagicCard.create(object_type: "card", name: "Mighty Leap", mtgo_id: 57238, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "24", foil:FALSE)
MagicCard.create(object_type: "card", name: "Myrsmith", mtgo_id: 57269, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "28", foil:TRUE)
MagicCard.create(object_type: "card", name: "Myrsmith", mtgo_id: 57268, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "28", foil:FALSE)
MagicCard.create(object_type: "card", name: "Otherworldly Journey", mtgo_id: 57401, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "30", foil:TRUE)
MagicCard.create(object_type: "card", name: "Otherworldly Journey", mtgo_id: 57400, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "30", foil:FALSE)
MagicCard.create(object_type: "card", name: "Raise the Alarm", mtgo_id: 57375, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "31", foil:TRUE)
MagicCard.create(object_type: "card", name: "Raise the Alarm", mtgo_id: 57374, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "31", foil:FALSE)
MagicCard.create(object_type: "card", name: "Sunspear Shikari", mtgo_id: 57263, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "35", foil:TRUE)
MagicCard.create(object_type: "card", name: "Sunspear Shikari", mtgo_id: 57262, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "35", foil:FALSE)
MagicCard.create(object_type: "card", name: "Daybreak Coronet", mtgo_id: 57387, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "14", foil:TRUE)
MagicCard.create(object_type: "card", name: "Daybreak Coronet", mtgo_id: 57386, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "14", foil:FALSE)
MagicCard.create(object_type: "card", name: "Flashfreeze", mtgo_id: 57499, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "45", foil:TRUE)
MagicCard.create(object_type: "card", name: "Flashfreeze", mtgo_id: 57498, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "45", foil:FALSE)
MagicCard.create(object_type: "card", name: "Hurkyl's Recall", mtgo_id: 57019, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "48", foil:TRUE)
MagicCard.create(object_type: "card", name: "Hurkyl's Recall", mtgo_id: 57018, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "48", foil:FALSE)
MagicCard.create(object_type: "card", name: "Mana Leak", mtgo_id: 57221, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "50", foil:TRUE)
MagicCard.create(object_type: "card", name: "Mana Leak", mtgo_id: 57220, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "50", foil:FALSE)
MagicCard.create(object_type: "card", name: "Narcolepsy", mtgo_id: 57197, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "52", foil:TRUE)
MagicCard.create(object_type: "card", name: "Narcolepsy", mtgo_id: 57196, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "52", foil:FALSE)
MagicCard.create(object_type: "card", name: "Remand", mtgo_id: 57373, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "55", foil:TRUE)
MagicCard.create(object_type: "card", name: "Remand", mtgo_id: 57372, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "55", foil:FALSE)
MagicCard.create(object_type: "card", name: "Telling Time", mtgo_id: 57445, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "61", foil:TRUE)
MagicCard.create(object_type: "card", name: "Telling Time", mtgo_id: 57444, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "61", foil:FALSE)
MagicCard.create(object_type: "card", name: "Thrummingbird", mtgo_id: 57249, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "65", foil:TRUE)
MagicCard.create(object_type: "card", name: "Thrummingbird", mtgo_id: 57248, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "65", foil:FALSE)
MagicCard.create(object_type: "card", name: "Wings of Velis Vel", mtgo_id: 57033, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "70", foil:TRUE)
MagicCard.create(object_type: "card", name: "Wings of Velis Vel", mtgo_id: 57032, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "70", foil:FALSE)
MagicCard.create(object_type: "card", name: "Bitterblossom", mtgo_id: 57055, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "71", foil:TRUE)
MagicCard.create(object_type: "card", name: "Bitterblossom", mtgo_id: 57054, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "71", foil:FALSE)
MagicCard.create(object_type: "card", name: "Bloodthrone Vampire", mtgo_id: 57215, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "72", foil:TRUE)
MagicCard.create(object_type: "card", name: "Bloodthrone Vampire", mtgo_id: 57214, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "72", foil:FALSE)
MagicCard.create(object_type: "card", name: "Dark Confidant", mtgo_id: 57345, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "75", foil:TRUE)
MagicCard.create(object_type: "card", name: "Dark Confidant", mtgo_id: 57344, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "75", foil:FALSE)
MagicCard.create(object_type: "card", name: "Duskhunter Bat", mtgo_id: 57303, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "81", foil:TRUE)
MagicCard.create(object_type: "card", name: "Duskhunter Bat", mtgo_id: 57302, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "81", foil:FALSE)
MagicCard.create(object_type: "card", name: "Nameless Inversion", mtgo_id: 57049, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "87", foil:TRUE)
MagicCard.create(object_type: "card", name: "Nameless Inversion", mtgo_id: 57048, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "87", foil:FALSE)
MagicCard.create(object_type: "card", name: "Reassembling Skeleton", mtgo_id: 57235, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "92", foil:TRUE)
MagicCard.create(object_type: "card", name: "Reassembling Skeleton", mtgo_id: 57234, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "92", foil:FALSE)
MagicCard.create(object_type: "card", name: "Shrivel", mtgo_id: 57191, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "95", foil:TRUE)
MagicCard.create(object_type: "card", name: "Shrivel", mtgo_id: 57190, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "95", foil:FALSE)
MagicCard.create(object_type: "card", name: "Sickle Ripper", mtgo_id: 57067, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "96", foil:TRUE)
MagicCard.create(object_type: "card", name: "Sickle Ripper", mtgo_id: 57066, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "96", foil:FALSE)
MagicCard.create(object_type: "card", name: "Sign in Blood", mtgo_id: 57139, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "97", foil:TRUE)
MagicCard.create(object_type: "card", name: "Sign in Blood", mtgo_id: 57138, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "97", foil:FALSE)
MagicCard.create(object_type: "card", name: "Blades of Velis Vel", mtgo_id: 57031, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "105", foil:TRUE)
MagicCard.create(object_type: "card", name: "Blades of Velis Vel", mtgo_id: 57030, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "105", foil:FALSE)
MagicCard.create(object_type: "card", name: "Combust", mtgo_id: 57229, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "110", foil:TRUE)
MagicCard.create(object_type: "card", name: "Combust", mtgo_id: 57228, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "110", foil:FALSE)
MagicCard.create(object_type: "card", name: "Goblin War Paint", mtgo_id: 57155, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "115", foil:TRUE)
MagicCard.create(object_type: "card", name: "Goblin War Paint", mtgo_id: 57154, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "115", foil:FALSE)
MagicCard.create(object_type: "card", name: "Smash to Smithereens", mtgo_id: 57069, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "124", foil:TRUE)
MagicCard.create(object_type: "card", name: "Smash to Smithereens", mtgo_id: 57068, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "124", foil:FALSE)
MagicCard.create(object_type: "card", name: "Smokebraider", mtgo_id: 57029, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "125", foil:TRUE)
MagicCard.create(object_type: "card", name: "Smokebraider", mtgo_id: 57028, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "125", foil:FALSE)
MagicCard.create(object_type: "card", name: "Soulbright Flamekin", mtgo_id: 57041, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "126", foil:TRUE)
MagicCard.create(object_type: "card", name: "Soulbright Flamekin", mtgo_id: 57040, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "126", foil:FALSE)
MagicCard.create(object_type: "card", name: "Stormblood Berserker", mtgo_id: 57305, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "130", foil:TRUE)
MagicCard.create(object_type: "card", name: "Stormblood Berserker", mtgo_id: 57304, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "130", foil:FALSE)
MagicCard.create(object_type: "card", name: "Tribal Flames", mtgo_id: 57355, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "132", foil:TRUE)
MagicCard.create(object_type: "card", name: "Tribal Flames", mtgo_id: 57354, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "132", foil:FALSE)
MagicCard.create(object_type: "card", name: "Viashino Slaughtermaster", mtgo_id: 57109, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "133", foil:TRUE)
MagicCard.create(object_type: "card", name: "Viashino Slaughtermaster", mtgo_id: 57108, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "133", foil:FALSE)
MagicCard.create(object_type: "card", name: "Aquastrand Spider", mtgo_id: 57491, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "140", foil:TRUE)
MagicCard.create(object_type: "card", name: "Aquastrand Spider", mtgo_id: 57490, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "140", foil:FALSE)
MagicCard.create(object_type: "card", name: "Gnarlid Pack", mtgo_id: 57177, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "144", foil:TRUE)
MagicCard.create(object_type: "card", name: "Gnarlid Pack", mtgo_id: 57176, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "144", foil:FALSE)
MagicCard.create(object_type: "card", name: "Nest Invader", mtgo_id: 57181, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "150", foil:TRUE)
MagicCard.create(object_type: "card", name: "Nest Invader", mtgo_id: 57180, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "150", foil:FALSE)
MagicCard.create(object_type: "card", name: "Plummet", mtgo_id: 57233, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "155", foil:TRUE)
MagicCard.create(object_type: "card", name: "Plummet", mtgo_id: 57232, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "155", foil:FALSE)
MagicCard.create(object_type: "card", name: "Rampant Growth", mtgo_id: 57011, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "157", foil:TRUE)
MagicCard.create(object_type: "card", name: "Rampant Growth", mtgo_id: 57010, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "157", foil:FALSE)
MagicCard.create(object_type: "card", name: "Tarmogoyf", mtgo_id: 57347, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "165", foil:TRUE)
MagicCard.create(object_type: "card", name: "Tarmogoyf", mtgo_id: 57346, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "165", foil:FALSE)
MagicCard.create(object_type: "card", name: "Ethercaste Knight", mtgo_id: 57133, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "175", foil:TRUE)
MagicCard.create(object_type: "card", name: "Ethercaste Knight", mtgo_id: 57132, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "175", foil:FALSE)
MagicCard.create(object_type: "card", name: "Dimir Guildmage", mtgo_id: 57443, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "192", foil:TRUE)
MagicCard.create(object_type: "card", name: "Dimir Guildmage", mtgo_id: 57442, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "192", foil:FALSE)
MagicCard.create(object_type: "card", name: "Agony Warp", mtgo_id: 57099, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "170", foil:TRUE)
MagicCard.create(object_type: "card", name: "Agony Warp", mtgo_id: 57098, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "170", foil:FALSE)
MagicCard.create(object_type: "card", name: "Necrogenesis", mtgo_id: 57095, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "181", foil:TRUE)
MagicCard.create(object_type: "card", name: "Necrogenesis", mtgo_id: 57094, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "181", foil:FALSE)
MagicCard.create(object_type: "card", name: "Boros Swiftblade", mtgo_id: 57423, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "172", foil:TRUE)
MagicCard.create(object_type: "card", name: "Boros Swiftblade", mtgo_id: 57422, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "172", foil:FALSE)
MagicCard.create(object_type: "card", name: "Selesnya Guildmage", mtgo_id: 57439, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "197", foil:TRUE)
MagicCard.create(object_type: "card", name: "Selesnya Guildmage", mtgo_id: 57438, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "197", foil:FALSE)
MagicCard.create(object_type: "card", name: "Sigil Blessing", mtgo_id: 57105, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "187", foil:TRUE)
MagicCard.create(object_type: "card", name: "Sigil Blessing", mtgo_id: 57104, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "187", foil:FALSE)
MagicCard.create(object_type: "card", name: "Alloy Myr", mtgo_id: 57309, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "201", foil:TRUE)
MagicCard.create(object_type: "card", name: "Alloy Myr", mtgo_id: 57308, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "201", foil:FALSE)
MagicCard.create(object_type: "card", name: "Blinding Souleater", mtgo_id: 57333, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "202", foil:TRUE)
MagicCard.create(object_type: "card", name: "Blinding Souleater", mtgo_id: 57332, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "202", foil:FALSE)
MagicCard.create(object_type: "card", name: "Cathodion", mtgo_id: 57377, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "203", foil:TRUE)
MagicCard.create(object_type: "card", name: "Cathodion", mtgo_id: 57376, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "203", foil:FALSE)
MagicCard.create(object_type: "card", name: "Etched Champion", mtgo_id: 57383, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "209", foil:TRUE)
MagicCard.create(object_type: "card", name: "Etched Champion", mtgo_id: 57382, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "209", foil:FALSE)
MagicCard.create(object_type: "card", name: "Long-Forgotten Gohei", mtgo_id: 57415, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "221", foil:TRUE)
MagicCard.create(object_type: "card", name: "Long-Forgotten Gohei", mtgo_id: 57414, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "221", foil:FALSE)
MagicCard.create(object_type: "card", name: "Sickleslicer", mtgo_id: 57315, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "228", foil:TRUE)
MagicCard.create(object_type: "card", name: "Sickleslicer", mtgo_id: 57314, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "228", foil:FALSE)
MagicCard.create(object_type: "card", name: "Sunforger", mtgo_id: 57425, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "232", foil:TRUE)
MagicCard.create(object_type: "card", name: "Sunforger", mtgo_id: 57424, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "232", foil:FALSE)
MagicCard.create(object_type: "card", name: "Tumble Magnet", mtgo_id: 57275, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "233", foil:TRUE)
MagicCard.create(object_type: "card", name: "Tumble Magnet", mtgo_id: 57274, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "233", foil:FALSE)
MagicCard.create(object_type: "card", name: "Arrest", mtgo_id: 57261, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "9", foil:TRUE)
MagicCard.create(object_type: "card", name: "Arrest", mtgo_id: 57260, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "9", foil:FALSE)
MagicCard.create(object_type: "card", name: "Fortify", mtgo_id: 57503, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "17", foil:TRUE)
MagicCard.create(object_type: "card", name: "Fortify", mtgo_id: 57502, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "17", foil:FALSE)
MagicCard.create(object_type: "card", name: "Mirror Entity", mtgo_id: 57045, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "26", foil:TRUE)
MagicCard.create(object_type: "card", name: "Mirror Entity", mtgo_id: 57044, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "26", foil:FALSE)
MagicCard.create(object_type: "card", name: "Oblivion Ring", mtgo_id: 57087, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "29", foil:TRUE)
MagicCard.create(object_type: "card", name: "Oblivion Ring", mtgo_id: 57086, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "29", foil:FALSE)
MagicCard.create(object_type: "card", name: "Terashi's Grasp", mtgo_id: 57421, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "37", foil:TRUE)
MagicCard.create(object_type: "card", name: "Terashi's Grasp", mtgo_id: 57420, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "37", foil:FALSE)
MagicCard.create(object_type: "card", name: "Waxmane Baku", mtgo_id: 57419, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "38", foil:TRUE)
MagicCard.create(object_type: "card", name: "Waxmane Baku", mtgo_id: 57418, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "38", foil:FALSE)
MagicCard.create(object_type: "card", name: "Mirran Crusader", mtgo_id: 57291, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "25", foil:TRUE)
MagicCard.create(object_type: "card", name: "Mirran Crusader", mtgo_id: 57290, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "25", foil:FALSE)
MagicCard.create(object_type: "card", name: "Skyhunter Skirmisher", mtgo_id: 57395, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "32", foil:TRUE)
MagicCard.create(object_type: "card", name: "Skyhunter Skirmisher", mtgo_id: 57394, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "32", foil:FALSE)
MagicCard.create(object_type: "card", name: "Cloud Elemental", mtgo_id: 57015, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "42", foil:TRUE)
MagicCard.create(object_type: "card", name: "Cloud Elemental", mtgo_id: 57014, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "42", foil:FALSE)
MagicCard.create(object_type: "card", name: "Steady Progress", mtgo_id: 57253, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "58", foil:TRUE)
MagicCard.create(object_type: "card", name: "Steady Progress", mtgo_id: 57252, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "58", foil:FALSE)
MagicCard.create(object_type: "card", name: "Vigean Graftmage", mtgo_id: 57485, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "68", foil:TRUE)
MagicCard.create(object_type: "card", name: "Vigean Graftmage", mtgo_id: 57484, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "68", foil:FALSE)
MagicCard.create(object_type: "card", name: "Stoic Rebuttal", mtgo_id: 57279, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "59", foil:TRUE)
MagicCard.create(object_type: "card", name: "Stoic Rebuttal", mtgo_id: 57278, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "59", foil:FALSE)
MagicCard.create(object_type: "card", name: "Surrakar Spellblade", mtgo_id: 57217, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "60", foil:TRUE)
MagicCard.create(object_type: "card", name: "Surrakar Spellblade", mtgo_id: 57216, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "60", foil:FALSE)
MagicCard.create(object_type: "card", name: "Vendilion Clique", mtgo_id: 57381, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "67", foil:TRUE)
MagicCard.create(object_type: "card", name: "Vendilion Clique", mtgo_id: 57380, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "67", foil:FALSE)
MagicCard.create(object_type: "card", name: "Daggerclaw Imp", mtgo_id: 57461, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "74", foil:TRUE)
MagicCard.create(object_type: "card", name: "Daggerclaw Imp", mtgo_id: 57460, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "74", foil:FALSE)
MagicCard.create(object_type: "card", name: "Ghostly Changeling", mtgo_id: 57025, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "83", foil:TRUE)
MagicCard.create(object_type: "card", name: "Ghostly Changeling", mtgo_id: 57024, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "83", foil:FALSE)
MagicCard.create(object_type: "card", name: "Grim Affliction", mtgo_id: 57317, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "84", foil:TRUE)
MagicCard.create(object_type: "card", name: "Grim Affliction", mtgo_id: 57316, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "84", foil:FALSE)
MagicCard.create(object_type: "card", name: "Thief of Hope", mtgo_id: 57407, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "100", foil:TRUE)
MagicCard.create(object_type: "card", name: "Thief of Hope", mtgo_id: 57406, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "100", foil:FALSE)
MagicCard.create(object_type: "card", name: "Waking Nightmare", mtgo_id: 57411, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "103", foil:TRUE)
MagicCard.create(object_type: "card", name: "Waking Nightmare", mtgo_id: 57410, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "103", foil:FALSE)
MagicCard.create(object_type: "card", name: "Dismember", mtgo_id: 57331, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "79", foil:TRUE)
MagicCard.create(object_type: "card", name: "Dismember", mtgo_id: 57330, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "79", foil:FALSE)
MagicCard.create(object_type: "card", name: "Necroskitter", mtgo_id: 57075, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "88", foil:TRUE)
MagicCard.create(object_type: "card", name: "Necroskitter", mtgo_id: 57074, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "88", foil:FALSE)
MagicCard.create(object_type: "card", name: "Blood Ogre", mtgo_id: 57301, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "106", foil:TRUE)
MagicCard.create(object_type: "card", name: "Blood Ogre", mtgo_id: 57300, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "106", foil:FALSE)
MagicCard.create(object_type: "card", name: "Dragonsoul Knight", mtgo_id: 57131, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "112", foil:TRUE)
MagicCard.create(object_type: "card", name: "Dragonsoul Knight", mtgo_id: 57130, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "112", foil:FALSE)
MagicCard.create(object_type: "card", name: "Incandescent Soulstoke", mtgo_id: 57035, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "119", foil:TRUE)
MagicCard.create(object_type: "card", name: "Incandescent Soulstoke", mtgo_id: 57034, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "119", foil:FALSE)
MagicCard.create(object_type: "card", name: "Inner-Flame Igniter", mtgo_id: 57027, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "120", foil:TRUE)
MagicCard.create(object_type: "card", name: "Inner-Flame Igniter", mtgo_id: 57026, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "120", foil:FALSE)
MagicCard.create(object_type: "card", name: "Matca Rioters", mtgo_id: 57111, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "148", foil:TRUE)
MagicCard.create(object_type: "card", name: "Matca Rioters", mtgo_id: 57110, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "148", foil:FALSE)
MagicCard.create(object_type: "card", name: "Sundering Vitae", mtgo_id: 57429, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "163", foil:TRUE)
MagicCard.create(object_type: "card", name: "Sundering Vitae", mtgo_id: 57428, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "163", foil:FALSE)
MagicCard.create(object_type: "card", name: "Scion of the Wild", mtgo_id: 57453, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "160", foil:TRUE)
MagicCard.create(object_type: "card", name: "Scion of the Wild", mtgo_id: 57452, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "160", foil:FALSE)
MagicCard.create(object_type: "card", name: "Pillory of the Sleepless", mtgo_id: 57385, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "183", foil:TRUE)
MagicCard.create(object_type: "card", name: "Pillory of the Sleepless", mtgo_id: 57384, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "183", foil:FALSE)
MagicCard.create(object_type: "card", name: "Restless Apparition", mtgo_id: 57083, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "196", foil:TRUE)
MagicCard.create(object_type: "card", name: "Restless Apparition", mtgo_id: 57082, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "196", foil:FALSE)
MagicCard.create(object_type: "card", name: "Shadowmage Infiltrator", mtgo_id: 57343, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "186", foil:TRUE)
MagicCard.create(object_type: "card", name: "Shadowmage Infiltrator", mtgo_id: 57342, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "186", foil:FALSE)
MagicCard.create(object_type: "card", name: "Electrolyze", mtgo_id: 57455, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "174", foil:TRUE)
MagicCard.create(object_type: "card", name: "Electrolyze", mtgo_id: 57454, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "174", foil:FALSE)
MagicCard.create(object_type: "card", name: "Fulminator Mage", mtgo_id: 57057, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "193", foil:TRUE)
MagicCard.create(object_type: "card", name: "Fulminator Mage", mtgo_id: 57056, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "193", foil:FALSE)
MagicCard.create(object_type: "card", name: "Ashenmoor Gouger", mtgo_id: 57071, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "190", foil:TRUE)
MagicCard.create(object_type: "card", name: "Ashenmoor Gouger", mtgo_id: 57070, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "190", foil:FALSE)
MagicCard.create(object_type: "card", name: "Hearthfire Hobgoblin", mtgo_id: 57081, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "194", foil:TRUE)
MagicCard.create(object_type: "card", name: "Hearthfire Hobgoblin", mtgo_id: 57080, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "194", foil:FALSE)
MagicCard.create(object_type: "card", name: "Lorescale Coatl", mtgo_id: 57137, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "179", foil:TRUE)
MagicCard.create(object_type: "card", name: "Lorescale Coatl", mtgo_id: 57136, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "179", foil:FALSE)
MagicCard.create(object_type: "card", name: "Plaxcaster Frogling", mtgo_id: 57481, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "184", foil:TRUE)
MagicCard.create(object_type: "card", name: "Plaxcaster Frogling", mtgo_id: 57480, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "184", foil:FALSE)
MagicCard.create(object_type: "card", name: "Etched Oracle", mtgo_id: 57399, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "211", foil:TRUE)
MagicCard.create(object_type: "card", name: "Etched Oracle", mtgo_id: 57398, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "211", foil:FALSE)
MagicCard.create(object_type: "card", name: "Frogmite", mtgo_id: 57369, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "215", foil:TRUE)
MagicCard.create(object_type: "card", name: "Frogmite", mtgo_id: 57368, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "215", foil:FALSE)
MagicCard.create(object_type: "card", name: "Lodestone Golem", mtgo_id: 57169, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "219", foil:TRUE)
MagicCard.create(object_type: "card", name: "Lodestone Golem", mtgo_id: 57168, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "219", foil:FALSE)
MagicCard.create(object_type: "card", name: "Lodestone Myr", mtgo_id: 57359, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "220", foil:TRUE)
MagicCard.create(object_type: "card", name: "Lodestone Myr", mtgo_id: 57358, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "220", foil:FALSE)
MagicCard.create(object_type: "card", name: "Rusted Relic", mtgo_id: 57243, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "227", foil:TRUE)
MagicCard.create(object_type: "card", name: "Rusted Relic", mtgo_id: 57242, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "227", foil:FALSE)
MagicCard.create(object_type: "card", name: "Moonlit Strider", mtgo_id: 57417, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "27", foil:TRUE)
MagicCard.create(object_type: "card", name: "Moonlit Strider", mtgo_id: 57416, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "27", foil:FALSE)
MagicCard.create(object_type: "card", name: "Taj-Nar Swordsmith", mtgo_id: 57367, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "36", foil:TRUE)
MagicCard.create(object_type: "card", name: "Taj-Nar Swordsmith", mtgo_id: 57366, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "36", foil:FALSE)
MagicCard.create(object_type: "card", name: "Indomitable Archangel", mtgo_id: 57277, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "19", foil:TRUE)
MagicCard.create(object_type: "card", name: "Indomitable Archangel", mtgo_id: 57276, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "19", foil:FALSE)
MagicCard.create(object_type: "card", name: "Leyline of Sanctity", mtgo_id: 57223, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "23", foil:TRUE)
MagicCard.create(object_type: "card", name: "Leyline of Sanctity", mtgo_id: 57222, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "23", foil:FALSE)
MagicCard.create(object_type: "card", name: "Tezzeret's Gambit", mtgo_id: 57327, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "63", foil:TRUE)
MagicCard.create(object_type: "card", name: "Tezzeret's Gambit", mtgo_id: 57326, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "63", foil:FALSE)
MagicCard.create(object_type: "card", name: "Faerie Mechanist", mtgo_id: 57121, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "44", foil:TRUE)
MagicCard.create(object_type: "card", name: "Faerie Mechanist", mtgo_id: 57120, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "44", foil:FALSE)
MagicCard.create(object_type: "card", name: "Argent Sphinx", mtgo_id: 57281, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "41", foil:TRUE)
MagicCard.create(object_type: "card", name: "Argent Sphinx", mtgo_id: 57280, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "41", foil:FALSE)
MagicCard.create(object_type: "card", name: "Water Servant", mtgo_id: 57227, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "69", foil:TRUE)
MagicCard.create(object_type: "card", name: "Water Servant", mtgo_id: 57226, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "69", foil:FALSE)
MagicCard.create(object_type: "card", name: "Cryptic Command", mtgo_id: 57047, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "43", foil:TRUE)
MagicCard.create(object_type: "card", name: "Cryptic Command", mtgo_id: 57046, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "43", foil:FALSE)
MagicCard.create(object_type: "card", name: "Instill Infection", mtgo_id: 57251, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "85", foil:TRUE)
MagicCard.create(object_type: "card", name: "Instill Infection", mtgo_id: 57250, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "85", foil:FALSE)
MagicCard.create(object_type: "card", name: "Scavenger Drake", mtgo_id: 57093, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "93", foil:TRUE)
MagicCard.create(object_type: "card", name: "Scavenger Drake", mtgo_id: 57092, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "93", foil:FALSE)
MagicCard.create(object_type: "card", name: "Devouring Greed", mtgo_id: 57413, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "78", foil:TRUE)
MagicCard.create(object_type: "card", name: "Devouring Greed", mtgo_id: 57412, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "78", foil:FALSE)
MagicCard.create(object_type: "card", name: "Vampire Outcasts", mtgo_id: 57299, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "102", foil:TRUE)
MagicCard.create(object_type: "card", name: "Vampire Outcasts", mtgo_id: 57298, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "102", foil:FALSE)
MagicCard.create(object_type: "card", name: "Bloodshot Trainee", mtgo_id: 57247, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "107", foil:TRUE)
MagicCard.create(object_type: "card", name: "Bloodshot Trainee", mtgo_id: 57246, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "107", foil:FALSE)
MagicCard.create(object_type: "card", name: "Worldheart Phoenix", mtgo_id: 57103, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "135", foil:TRUE)
MagicCard.create(object_type: "card", name: "Worldheart Phoenix", mtgo_id: 57102, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "135", foil:FALSE)
MagicCard.create(object_type: "card", name: "Wrap in Flames", mtgo_id: 57195, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "136", foil:TRUE)
MagicCard.create(object_type: "card", name: "Wrap in Flames", mtgo_id: 57194, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "136", foil:FALSE)
MagicCard.create(object_type: "card", name: "Gorehorn Minotaurs", mtgo_id: 57211, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "116", foil:TRUE)
MagicCard.create(object_type: "card", name: "Gorehorn Minotaurs", mtgo_id: 57210, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "116", foil:FALSE)
MagicCard.create(object_type: "card", name: "Splinter Twin", mtgo_id: 57187, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "129", foil:TRUE)
MagicCard.create(object_type: "card", name: "Splinter Twin", mtgo_id: 57186, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "129", foil:FALSE)
MagicCard.create(object_type: "card", name: "Algae Gharial", mtgo_id: 57091, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "137", foil:TRUE)
MagicCard.create(object_type: "card", name: "Algae Gharial", mtgo_id: 57090, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "137", foil:FALSE)
MagicCard.create(object_type: "card", name: "Karplusan Strider", mtgo_id: 57497, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "145", foil:TRUE)
MagicCard.create(object_type: "card", name: "Karplusan Strider", mtgo_id: 57496, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "145", foil:FALSE)
MagicCard.create(object_type: "card", name: "Kavu Primarch", mtgo_id: 57013, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "146", foil:TRUE)
MagicCard.create(object_type: "card", name: "Kavu Primarch", mtgo_id: 57012, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "146", foil:FALSE)
MagicCard.create(object_type: "card", name: "Kozilek's Predator", mtgo_id: 57213, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "147", foil:TRUE)
MagicCard.create(object_type: "card", name: "Kozilek's Predator", mtgo_id: 57212, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "147", foil:FALSE)
MagicCard.create(object_type: "card", name: "Cytoplast Root-Kin", mtgo_id: 57483, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "143", foil:TRUE)
MagicCard.create(object_type: "card", name: "Cytoplast Root-Kin", mtgo_id: 57482, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "143", foil:FALSE)
MagicCard.create(object_type: "card", name: "Wolfbriar Elemental", mtgo_id: 57171, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "169", foil:TRUE)
MagicCard.create(object_type: "card", name: "Wolfbriar Elemental", mtgo_id: 57170, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "169", foil:FALSE)
MagicCard.create(object_type: "card", name: "Swans of Bryn Argoll", mtgo_id: 57059, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "199", foil:TRUE)
MagicCard.create(object_type: "card", name: "Swans of Bryn Argoll", mtgo_id: 57058, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "199", foil:FALSE)
MagicCard.create(object_type: "card", name: "Ghost Council of Orzhova", mtgo_id: 57459, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "176", foil:TRUE)
MagicCard.create(object_type: "card", name: "Ghost Council of Orzhova", mtgo_id: 57458, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "176", foil:FALSE)
MagicCard.create(object_type: "card", name: "Shrewd Hatchling", mtgo_id: 57077, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "198", foil:TRUE)
MagicCard.create(object_type: "card", name: "Shrewd Hatchling", mtgo_id: 57076, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "198", foil:FALSE)
MagicCard.create(object_type: "card", name: "Wrecking Ball", mtgo_id: 57495, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "189", foil:TRUE)
MagicCard.create(object_type: "card", name: "Wrecking Ball", mtgo_id: 57494, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "189", foil:FALSE)
MagicCard.create(object_type: "card", name: "Creakwood Liege", mtgo_id: 57073, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "191", foil:TRUE)
MagicCard.create(object_type: "card", name: "Creakwood Liege", mtgo_id: 57072, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "191", foil:FALSE)
MagicCard.create(object_type: "card", name: "Wilt-Leaf Liege", mtgo_id: 57065, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "200", foil:TRUE)
MagicCard.create(object_type: "card", name: "Wilt-Leaf Liege", mtgo_id: 57064, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "200", foil:FALSE)
MagicCard.create(object_type: "card", name: "Mystic Snake", mtgo_id: 57273, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "180", foil:TRUE)
MagicCard.create(object_type: "card", name: "Mystic Snake", mtgo_id: 57272, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "180", foil:FALSE)
MagicCard.create(object_type: "card", name: "Etched Monstrosity", mtgo_id: 57321, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "210", foil:TRUE)
MagicCard.create(object_type: "card", name: "Etched Monstrosity", mtgo_id: 57320, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "210", foil:FALSE)
MagicCard.create(object_type: "card", name: "Precursor Golem", mtgo_id: 57257, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "225", foil:TRUE)
MagicCard.create(object_type: "card", name: "Precursor Golem", mtgo_id: 57256, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "225", foil:FALSE)
MagicCard.create(object_type: "card", name: "Skyreach Manta", mtgo_id: 57397, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "229", foil:TRUE)
MagicCard.create(object_type: "card", name: "Skyreach Manta", mtgo_id: 57396, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "229", foil:FALSE)
MagicCard.create(object_type: "card", name: "Conclave Phalanx", mtgo_id: 57447, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "12", foil:TRUE)
MagicCard.create(object_type: "card", name: "Conclave Phalanx", mtgo_id: 57446, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "12", foil:FALSE)
MagicCard.create(object_type: "card", name: "Battlegrace Angel", mtgo_id: 57101, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "10", foil:TRUE)
MagicCard.create(object_type: "card", name: "Battlegrace Angel", mtgo_id: 57100, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "10", foil:FALSE)
MagicCard.create(object_type: "card", name: "Hikari, Twilight Guardian", mtgo_id: 57403, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "18", foil:TRUE)
MagicCard.create(object_type: "card", name: "Hikari, Twilight Guardian", mtgo_id: 57402, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "18", foil:FALSE)
MagicCard.create(object_type: "card", name: "Air Servant", mtgo_id: 57237, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "40", foil:TRUE)
MagicCard.create(object_type: "card", name: "Air Servant", mtgo_id: 57236, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "40", foil:FALSE)
MagicCard.create(object_type: "card", name: "Helium Squirter", mtgo_id: 57493, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "47", foil:TRUE)
MagicCard.create(object_type: "card", name: "Helium Squirter", mtgo_id: 57492, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "47", foil:FALSE)
MagicCard.create(object_type: "card", name: "Mulldrifter", mtgo_id: 57023, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "51", foil:TRUE)
MagicCard.create(object_type: "card", name: "Mulldrifter", mtgo_id: 57022, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "51", foil:FALSE)
MagicCard.create(object_type: "card", name: "Thoughtcast", mtgo_id: 57361, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "64", foil:TRUE)
MagicCard.create(object_type: "card", name: "Thoughtcast", mtgo_id: 57360, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "64", foil:FALSE)
MagicCard.create(object_type: "card", name: "Inexorable Tide", mtgo_id: 57255, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "49", foil:TRUE)
MagicCard.create(object_type: "card", name: "Inexorable Tide", mtgo_id: 57254, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "49", foil:FALSE)
MagicCard.create(object_type: "card", name: "Tezzeret the Seeker", mtgo_id: 57089, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "62", foil:TRUE)
MagicCard.create(object_type: "card", name: "Tezzeret the Seeker", mtgo_id: 57088, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "62", foil:FALSE)
MagicCard.create(object_type: "card", name: "Dread Drone", mtgo_id: 57193, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "80", foil:TRUE)
MagicCard.create(object_type: "card", name: "Dread Drone", mtgo_id: 57192, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "80", foil:FALSE)
MagicCard.create(object_type: "card", name: "Endrek Sahr, Master Breeder", mtgo_id: 57501, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "82", foil:TRUE)
MagicCard.create(object_type: "card", name: "Endrek Sahr, Master Breeder", mtgo_id: 57500, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "82", foil:FALSE)
MagicCard.create(object_type: "card", name: "Scuttling Death", mtgo_id: 57409, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "94", foil:TRUE)
MagicCard.create(object_type: "card", name: "Scuttling Death", mtgo_id: 57408, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "94", foil:FALSE)
MagicCard.create(object_type: "card", name: "Spread the Sickness", mtgo_id: 57295, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "98", foil:TRUE)
MagicCard.create(object_type: "card", name: "Spread the Sickness", mtgo_id: 57294, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "98", foil:FALSE)
MagicCard.create(object_type: "card", name: "Puppeteer Clique", mtgo_id: 57061, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "91", foil:TRUE)
MagicCard.create(object_type: "card", name: "Puppeteer Clique", mtgo_id: 57060, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "91", foil:FALSE)
MagicCard.create(object_type: "card", name: "Kiki-Jiki, Mirror Breaker", mtgo_id: 57341, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "121", foil:TRUE)
MagicCard.create(object_type: "card", name: "Kiki-Jiki, Mirror Breaker", mtgo_id: 57340, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "121", foil:FALSE)
MagicCard.create(object_type: "card", name: "Thunderblust", mtgo_id: 57085, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "131", foil:TRUE)
MagicCard.create(object_type: "card", name: "Thunderblust", mtgo_id: 57084, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "131", foil:FALSE)
MagicCard.create(object_type: "card", name: "All Suns' Dawn", mtgo_id: 57363, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "138", foil:TRUE)
MagicCard.create(object_type: "card", name: "All Suns' Dawn", mtgo_id: 57362, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "138", foil:FALSE)
MagicCard.create(object_type: "card", name: "Ant Queen", mtgo_id: 57145, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "139", foil:TRUE)
MagicCard.create(object_type: "card", name: "Ant Queen", mtgo_id: 57144, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "139", foil:FALSE)
MagicCard.create(object_type: "card", name: "Bestial Menace", mtgo_id: 57163, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "141", foil:TRUE)
MagicCard.create(object_type: "card", name: "Bestial Menace", mtgo_id: 57162, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "141", foil:FALSE)
MagicCard.create(object_type: "card", name: "Overwhelming Stampede", mtgo_id: 57225, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "153", foil:TRUE)
MagicCard.create(object_type: "card", name: "Overwhelming Stampede", mtgo_id: 57224, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "153", foil:FALSE)
MagicCard.create(object_type: "card", name: "Scatter the Seeds", mtgo_id: 57433, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "159", foil:TRUE)
MagicCard.create(object_type: "card", name: "Scatter the Seeds", mtgo_id: 57432, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "159", foil:FALSE)
MagicCard.create(object_type: "card", name: "Glassdust Hulk", mtgo_id: 57135, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "177", foil:TRUE)
MagicCard.create(object_type: "card", name: "Glassdust Hulk", mtgo_id: 57134, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "177", foil:FALSE)
MagicCard.create(object_type: "card", name: "Horde of Notions", mtgo_id: 57039, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "178", foil:TRUE)
MagicCard.create(object_type: "card", name: "Horde of Notions", mtgo_id: 57038, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "178", foil:FALSE)
MagicCard.create(object_type: "card", name: "Nobilis of War", mtgo_id: 57079, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "195", foil:TRUE)
MagicCard.create(object_type: "card", name: "Nobilis of War", mtgo_id: 57078, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "195", foil:FALSE)
MagicCard.create(object_type: "card", name: "Æthersnipe", mtgo_id: 57051, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "39", foil:TRUE)
MagicCard.create(object_type: "card", name: "Æthersnipe", mtgo_id: 57050, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "39", foil:FALSE)
MagicCard.create(object_type: "card", name: "Somber Hoverguard", mtgo_id: 57357, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "57", foil:TRUE)
MagicCard.create(object_type: "card", name: "Somber Hoverguard", mtgo_id: 57356, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "57", foil:FALSE)
MagicCard.create(object_type: "card", name: "Novijen Sages", mtgo_id: 57479, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "53", foil:TRUE)
MagicCard.create(object_type: "card", name: "Novijen Sages", mtgo_id: 57478, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "53", foil:FALSE)
MagicCard.create(object_type: "card", name: "Guile", mtgo_id: 57053, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "46", foil:TRUE)
MagicCard.create(object_type: "card", name: "Guile", mtgo_id: 57052, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "46", foil:FALSE)
MagicCard.create(object_type: "card", name: "Midnight Banshee", mtgo_id: 57063, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "86", foil:TRUE)
MagicCard.create(object_type: "card", name: "Midnight Banshee", mtgo_id: 57062, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "86", foil:FALSE)
MagicCard.create(object_type: "card", name: "Fiery Fall", mtgo_id: 57115, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "113", foil:TRUE)
MagicCard.create(object_type: "card", name: "Fiery Fall", mtgo_id: 57114, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "113", foil:FALSE)
MagicCard.create(object_type: "card", name: "Spitebellows", mtgo_id: 57037, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "128", foil:TRUE)
MagicCard.create(object_type: "card", name: "Spitebellows", mtgo_id: 57036, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "128", foil:FALSE)
MagicCard.create(object_type: "card", name: "Hellkite Charger", mtgo_id: 57157, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "118", foil:TRUE)
MagicCard.create(object_type: "card", name: "Hellkite Charger", mtgo_id: 57156, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "118", foil:FALSE)
MagicCard.create(object_type: "card", name: "Skarrgan Firebird", mtgo_id: 57465, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "123", foil:TRUE)
MagicCard.create(object_type: "card", name: "Skarrgan Firebird", mtgo_id: 57464, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "123", foil:FALSE)
MagicCard.create(object_type: "card", name: "Wildfire", mtgo_id: 57021, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "134", foil:TRUE)
MagicCard.create(object_type: "card", name: "Wildfire", mtgo_id: 57020, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "134", foil:FALSE)
MagicCard.create(object_type: "card", name: "Sylvan Bounty", mtgo_id: 57117, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "164", foil:TRUE)
MagicCard.create(object_type: "card", name: "Sylvan Bounty", mtgo_id: 57116, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "164", foil:FALSE)
MagicCard.create(object_type: "card", name: "Primeval Titan", mtgo_id: 57231, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "156", foil:TRUE)
MagicCard.create(object_type: "card", name: "Primeval Titan", mtgo_id: 57230, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "156", foil:FALSE)
MagicCard.create(object_type: "card", name: "Root-Kin Ally", mtgo_id: 57449, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "158", foil:TRUE)
MagicCard.create(object_type: "card", name: "Root-Kin Ally", mtgo_id: 57448, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "158", foil:FALSE)
MagicCard.create(object_type: "card", name: "Spectral Procession", mtgo_id: 57349, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "33", foil:TRUE)
MagicCard.create(object_type: "card", name: "Spectral Procession", mtgo_id: 57348, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "33", foil:FALSE)
MagicCard.create(object_type: "card", name: "Niv-Mizzet, the Firemind", mtgo_id: 57463, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "182", foil:TRUE)
MagicCard.create(object_type: "card", name: "Niv-Mizzet, the Firemind", mtgo_id: 57462, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "182", foil:FALSE)
MagicCard.create(object_type: "card", name: "Drooling Groodion", mtgo_id: 57441, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "173", foil:TRUE)
MagicCard.create(object_type: "card", name: "Drooling Groodion", mtgo_id: 57440, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "173", foil:FALSE)
MagicCard.create(object_type: "card", name: "Vengeful Rebirth", mtgo_id: 57097, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "188", foil:TRUE)
MagicCard.create(object_type: "card", name: "Vengeful Rebirth", mtgo_id: 57096, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "188", foil:FALSE)
MagicCard.create(object_type: "card", name: "All Is Dust", mtgo_id: 57203, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "1", foil:TRUE)
MagicCard.create(object_type: "card", name: "All Is Dust", mtgo_id: 57202, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "1", foil:FALSE)
MagicCard.create(object_type: "card", name: "Karn Liberated", mtgo_id: 57311, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "4", foil:TRUE)
MagicCard.create(object_type: "card", name: "Karn Liberated", mtgo_id: 57310, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "4", foil:FALSE)
MagicCard.create(object_type: "card", name: "Myr Enforcer", mtgo_id: 57371, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "224", foil:TRUE)
MagicCard.create(object_type: "card", name: "Myr Enforcer", mtgo_id: 57370, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "224", foil:FALSE)
MagicCard.create(object_type: "card", name: "Elesh Norn, Grand Cenobite", mtgo_id: 57313, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "16", foil:TRUE)
MagicCard.create(object_type: "card", name: "Elesh Norn, Grand Cenobite", mtgo_id: 57312, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "16", foil:FALSE)
MagicCard.create(object_type: "card", name: "Overwhelm", mtgo_id: 57451, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "152", foil:TRUE)
MagicCard.create(object_type: "card", name: "Overwhelm", mtgo_id: 57450, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "152", foil:FALSE)
MagicCard.create(object_type: "card", name: "Pelakka Wurm", mtgo_id: 57199, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "154", foil:TRUE)
MagicCard.create(object_type: "card", name: "Pelakka Wurm", mtgo_id: 57198, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "154", foil:FALSE)
MagicCard.create(object_type: "card", name: "Ulamog's Crusher", mtgo_id: 57205, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "7", foil:TRUE)
MagicCard.create(object_type: "card", name: "Ulamog's Crusher", mtgo_id: 57204, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "7", foil:FALSE)
MagicCard.create(object_type: "card", name: "Qumulox", mtgo_id: 57365, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "54", foil:TRUE)
MagicCard.create(object_type: "card", name: "Qumulox", mtgo_id: 57364, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "54", foil:FALSE)
MagicCard.create(object_type: "card", name: "Artisan of Kozilek", mtgo_id: 57183, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "2", foil:TRUE)
MagicCard.create(object_type: "card", name: "Artisan of Kozilek", mtgo_id: 57182, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "2", foil:FALSE)
MagicCard.create(object_type: "card", name: "Iona, Shield of Emeria", mtgo_id: 57159, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "20", foil:TRUE)
MagicCard.create(object_type: "card", name: "Iona, Shield of Emeria", mtgo_id: 57158, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "20", foil:FALSE)
MagicCard.create(object_type: "card", name: "Kozilek, Butcher of Truth", mtgo_id: 57201, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "5", foil:TRUE)
MagicCard.create(object_type: "card", name: "Kozilek, Butcher of Truth", mtgo_id: 57200, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "5", foil:FALSE)
MagicCard.create(object_type: "card", name: "Ulamog, the Infinite Gyre", mtgo_id: 57207, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "6", foil:TRUE)
MagicCard.create(object_type: "card", name: "Ulamog, the Infinite Gyre", mtgo_id: 57206, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "6", foil:FALSE)
MagicCard.create(object_type: "card", name: "Emrakul, the Aeons Torn", mtgo_id: 57185, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "3", foil:TRUE)
MagicCard.create(object_type: "card", name: "Emrakul, the Aeons Torn", mtgo_id: 57184, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "3", foil:FALSE)
MagicCard.create(object_type: "card", name: "Chimeric Mass", mtgo_id: 57271, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "204", foil:TRUE)
MagicCard.create(object_type: "card", name: "Chimeric Mass", mtgo_id: 57270, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "204", foil:FALSE)
MagicCard.create(object_type: "card", name: "Repeal", mtgo_id: 57379, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "56", foil:TRUE)
MagicCard.create(object_type: "card", name: "Repeal", mtgo_id: 57378, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "56", foil:FALSE)
MagicCard.create(object_type: "card", name: "Banefire", mtgo_id: 57129, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "104", foil:TRUE)
MagicCard.create(object_type: "card", name: "Banefire", mtgo_id: 57128, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "104", foil:FALSE)
MagicCard.create(object_type: "card", name: "Thrive", mtgo_id: 57487, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "166", foil:TRUE)
MagicCard.create(object_type: "card", name: "Thrive", mtgo_id: 57486, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "166", foil:FALSE)
MagicCard.create(object_type: "card", name: "Death Denied", mtgo_id: 57353, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "76", foil:TRUE)
MagicCard.create(object_type: "card", name: "Death Denied", mtgo_id: 57352, rarity: "common", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "76", foil:FALSE)
MagicCard.create(object_type: "card", name: "Profane Command", mtgo_id: 57043, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "90", foil:TRUE)
MagicCard.create(object_type: "card", name: "Profane Command", mtgo_id: 57042, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "90", foil:FALSE)
MagicCard.create(object_type: "card", name: "Comet Storm", mtgo_id: 57173, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "111", foil:TRUE)
MagicCard.create(object_type: "card", name: "Comet Storm", mtgo_id: 57172, rarity: "mythic", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "111", foil:FALSE)
MagicCard.create(object_type: "card", name: "Apocalypse Hydra", mtgo_id: 57125, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "171", foil:TRUE)
MagicCard.create(object_type: "card", name: "Apocalypse Hydra", mtgo_id: 57124, rarity: "rare", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "171", foil:FALSE)
MagicCard.create(object_type: "card", name: "Savage Twister", mtgo_id: 57283, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "185", foil:TRUE)
MagicCard.create(object_type: "card", name: "Savage Twister", mtgo_id: 57282, rarity: "uncommon", magic_set_id: MagicSet.find_by(code: "MM2").id, collector_number: "185", foil:FALSE)
