MagicCard.create(object_type: "vanguard", name: "Avatar - Ashling, the Extinguisher", mtgo_id: 29906 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "81")
MagicCard.create(object_type: "vanguard", name: "Avatar - Aeon Chronicler", mtgo_id: 42835 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "142")
MagicCard.create(object_type: "vanguard", name: "Avatar - Ajani Steadfast", mtgo_id: 53812 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "199")
MagicCard.create(object_type: "vanguard", name: "Avatar - Akroma, Angel of Wrath", mtgo_id: 19 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "33")
MagicCard.create(object_type: "vanguard", name: "Avatar - Anowon, the Ruin Sage", mtgo_id: 35804 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "109")
MagicCard.create(object_type: "vanguard", name: "Avatar - Arcanis, the Omnipotent", mtgo_id: 26957 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "70")
MagicCard.create(object_type: "vanguard", name: "Avatar - Arcbound Overseer", mtgo_id: 27 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "42")
MagicCard.create(object_type: "vanguard", name: "Avatar - Archangel of Thune", mtgo_id: 49804 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "163")
MagicCard.create(object_type: "vanguard", name: "Avatar - Armament Master", mtgo_id: 35181 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "101")
MagicCard.create(object_type: "vanguard", name: "Avatar - Ashling the Pilgrim", mtgo_id: 28161 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "73")
MagicCard.create(object_type: "vanguard", name: "Avatar - Aurelia, the Warleader", mtgo_id: 47951 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "159")
MagicCard.create(object_type: "vanguard", name: "Avatar - Auriok", mtgo_id: 39012 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "125")
MagicCard.create(object_type: "vanguard", name: "Avatar - Avacyn, Angel of Hope", mtgo_id: 44294 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "148")
MagicCard.create(object_type: "vanguard", name: "Avatar - Avatar of Woe", mtgo_id: 43048 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "144")
MagicCard.create(object_type: "vanguard", name: "Avatar - Axe of the Warmonger", mtgo_id: 52548 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "192")
MagicCard.create(object_type: "vanguard", name: "Avatar - Balance", mtgo_id: 39010 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "123")
MagicCard.create(object_type: "vanguard", name: "Avatar - Battle the Horde", mtgo_id: 51887 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "186")
MagicCard.create(object_type: "vanguard", name: "Avatar - Birds of Paradise", mtgo_id: 12 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "8")
MagicCard.create(object_type: "vanguard", name: "Avatar - Black Lotus", mtgo_id: 52553 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "197")
MagicCard.create(object_type: "vanguard", name: "Avatar - Bloodline Keeper", mtgo_id: 42833 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "140")
MagicCard.create(object_type: "vanguard", name: "Avatar - Borborygmos", mtgo_id: 47950 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "158")
MagicCard.create(object_type: "vanguard", name: "Avatar - Bosh, Iron Golem", mtgo_id: 24 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "39")
MagicCard.create(object_type: "vanguard", name: "Avatar - Bow of the Hunter", mtgo_id: 52549 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "193")
MagicCard.create(object_type: "vanguard", name: "Avatar - Braids, Conjurer Adept", mtgo_id: 24848 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "66")
MagicCard.create(object_type: "vanguard", name: "Avatar - Brimaz, King of Oreskos", mtgo_id: 51886 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "185")
MagicCard.create(object_type: "vanguard", name: "Avatar - Chandra, Pyromaster", mtgo_id: 53815 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "202")
MagicCard.create(object_type: "vanguard", name: "Avatar - Chronatog", mtgo_id: 23963 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "59")
MagicCard.create(object_type: "vanguard", name: "Avatar - Cloak of the Philosopher", mtgo_id: 52546 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "190")
MagicCard.create(object_type: "vanguard", name: "Avatar - Commander Greven il-Vec", mtgo_id: 35199 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "103")
MagicCard.create(object_type: "vanguard", name: "Avatar - Dack Fayden", mtgo_id: 52554 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "198")
MagicCard.create(object_type: "vanguard", name: "Avatar - Dakkon Blackblade", mtgo_id: 26959 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "72")
MagicCard.create(object_type: "vanguard", name: "Avatar - Dakra Mystic", mtgo_id: 52543 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "187")
MagicCard.create(object_type: "vanguard", name: "Avatar - Dauntless Escort", mtgo_id: 32208 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "94")
MagicCard.create(object_type: "vanguard", name: "Avatar - Diamond Faerie", mtgo_id: 24833 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "63")
MagicCard.create(object_type: "vanguard", name: "Avatar - Echo Mage", mtgo_id: 36832 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "114")
MagicCard.create(object_type: "vanguard", name: "Avatar - Eight-and-a-Half-Tails", mtgo_id: 30 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "45")
MagicCard.create(object_type: "vanguard", name: "Avatar - Eladamri, Lord of Leaves", mtgo_id: 31499 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "88")
MagicCard.create(object_type: "vanguard", name: "Avatar - Elesh Norn, Grand Cenobite", mtgo_id: 40029 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "131")
MagicCard.create(object_type: "vanguard", name: "Avatar - Elvish Champion", mtgo_id: 22 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "37")
MagicCard.create(object_type: "vanguard", name: "Avatar - Emmara Tandris", mtgo_id: 48569 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "162")
MagicCard.create(object_type: "vanguard", name: "Avatar - Enigma Sphinx", mtgo_id: 32209 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "95")
MagicCard.create(object_type: "vanguard", name: "Avatar - Erhnam Djinn", mtgo_id: 16 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "27")
MagicCard.create(object_type: "vanguard", name: "Avatar - Ertai, Wizard Adept", mtgo_id: 35198 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "102")
MagicCard.create(object_type: "vanguard", name: "Avatar - Etched Oracle", mtgo_id: 29 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "44")
MagicCard.create(object_type: "vanguard", name: "Avatar - Face the Hydra", mtgo_id: 50078 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "167")
MagicCard.create(object_type: "vanguard", name: "Avatar - Fallen Angel", mtgo_id: 13 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "9")
MagicCard.create(object_type: "vanguard", name: "Avatar - Figure of Destiny", mtgo_id: 29907 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "82")
MagicCard.create(object_type: "vanguard", name: "Avatar - Flametongue Kavu", mtgo_id: 14 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "14")
MagicCard.create(object_type: "vanguard", name: "Avatar - Frenetic Efreet", mtgo_id: 38 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "53")
MagicCard.create(object_type: "vanguard", name: "Avatar - Freyalise, Llanowar's Fury", mtgo_id: 54567 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "207")
MagicCard.create(object_type: "vanguard", name: "Avatar - Garruk, Apex Predator", mtgo_id: 53817 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "204")
MagicCard.create(object_type: "vanguard", name: "Avatar - Geth, Lord of the Vault", mtgo_id: 37824 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "119")
MagicCard.create(object_type: "vanguard", name: "Avatar - Ghave, Guru of Spores", mtgo_id: 41103 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "134")
MagicCard.create(object_type: "vanguard", name: "Avatar - Glissa, the Traitor", mtgo_id: 39617 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "127")
MagicCard.create(object_type: "vanguard", name: "Avatar - Goblin Warchief", mtgo_id: 10 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "5")
MagicCard.create(object_type: "vanguard", name: "Avatar - Goblin Welder", mtgo_id: 36899 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "115")
MagicCard.create(object_type: "vanguard", name: "Avatar - Grimgrin, Corpse-Born", mtgo_id: 42834 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "141")
MagicCard.create(object_type: "vanguard", name: "Avatar - Grinning Demon", mtgo_id: 17 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "29")
MagicCard.create(object_type: "vanguard", name: "Avatar - Griselbrand", mtgo_id: 44293 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "147")
MagicCard.create(object_type: "vanguard", name: "Avatar - Haakon, Stromgald Scourge", mtgo_id: 24832 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "62")
MagicCard.create(object_type: "vanguard", name: "Avatar - Heartwood Storyteller", mtgo_id: 26560 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "68")
MagicCard.create(object_type: "vanguard", name: "Avatar - Hell's Caretaker", mtgo_id: 36 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "51")
MagicCard.create(object_type: "vanguard", name: "Avatar - Hermit Druid", mtgo_id: 32102 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "93")
MagicCard.create(object_type: "vanguard", name: "Avatar - Hero of Oxid Ridge", mtgo_id: 39616 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "126")
MagicCard.create(object_type: "vanguard", name: "Avatar - Higure, the Still Wind", mtgo_id: 32 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "47")
MagicCard.create(object_type: "vanguard", name: "Avatar - Hythonia the Cruel", mtgo_id: 50076 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "165")
MagicCard.create(object_type: "vanguard", name: "Avatar - Ink-Eyes, Servant of Oni", mtgo_id: 33 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "48")
MagicCard.create(object_type: "vanguard", name: "Avatar - Isperia, Supreme Judge", mtgo_id: 46842 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "153")
MagicCard.create(object_type: "vanguard", name: "Avatar - Jace Beleren", mtgo_id: 41621 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "139")
MagicCard.create(object_type: "vanguard", name: "Avatar - Jace, the Living Guildpact", mtgo_id: 53813 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "200")
MagicCard.create(object_type: "vanguard", name: "Avatar - Jarad, Lich Lord of the Golgari", mtgo_id: 46840 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "151")
MagicCard.create(object_type: "vanguard", name: "Avatar - Jaya Ballard", mtgo_id: 24846 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "64")
MagicCard.create(object_type: "vanguard", name: "Avatar - Jhoira of the Ghitu", mtgo_id: 26561 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "69")
MagicCard.create(object_type: "vanguard", name: "Avatar - Joraga Warcaller", mtgo_id: 35805 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "110")
MagicCard.create(object_type: "vanguard", name: "Avatar - Judge's Familiar", mtgo_id: 52552 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "196")
MagicCard.create(object_type: "vanguard", name: "Avatar - Kaalia of the Vast", mtgo_id: 41101 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "132")
MagicCard.create(object_type: "vanguard", name: "Avatar - Karn, Silver Golem", mtgo_id: 35842 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "111")
MagicCard.create(object_type: "vanguard", name: "Avatar - Karona, False God", mtgo_id: 20 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "34")
MagicCard.create(object_type: "vanguard", name: "Avatar - Knight Exemplar", mtgo_id: 37588 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "117")
MagicCard.create(object_type: "vanguard", name: "Avatar - Krenko, Mob Boss", mtgo_id: 46020 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "150")
MagicCard.create(object_type: "vanguard", name: "Avatar - Kresh the Bloodbraided", mtgo_id: 30842 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "87")
MagicCard.create(object_type: "vanguard", name: "Avatar - Lash of the Tyrant", mtgo_id: 52547 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "191")
MagicCard.create(object_type: "vanguard", name: "Avatar - Lazav, Dimir Mastermind", mtgo_id: 47949 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "157")
MagicCard.create(object_type: "vanguard", name: "Avatar - Liliana Vess", mtgo_id: 53814 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "201")
MagicCard.create(object_type: "vanguard", name: "Avatar - Loxodon Hierarch", mtgo_id: 39 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "54")
MagicCard.create(object_type: "vanguard", name: "Avatar - Lyzolda, the Blood Witch", mtgo_id: 23964 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "60")
MagicCard.create(object_type: "vanguard", name: "Avatar - Maelstrom Archangel", mtgo_id: 31949 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "91")
MagicCard.create(object_type: "vanguard", name: "Avatar - Malfegor", mtgo_id: 31948 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "90")
MagicCard.create(object_type: "vanguard", name: "Avatar - Maralen of the Mornsong", mtgo_id: 28942 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "78")
MagicCard.create(object_type: "vanguard", name: "Avatar - Maro", mtgo_id: 37 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "52")
MagicCard.create(object_type: "vanguard", name: "Avatar - Master of the Wild Hunt", mtgo_id: 33091 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "96")
MagicCard.create(object_type: "vanguard", name: "Avatar - Mayael the Anima", mtgo_id: 30841 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "86")
MagicCard.create(object_type: "vanguard", name: "Avatar - Mirko Vosk, Mind Drinker", mtgo_id: 48568 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "161")
MagicCard.create(object_type: "vanguard", name: "Avatar - Mirri the Cursed", mtgo_id: 24849 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "67")
MagicCard.create(object_type: "vanguard", name: "Avatar - Mirror Entity", mtgo_id: 28162 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "74")
MagicCard.create(object_type: "vanguard", name: "Avatar - Momir Vig, Simic Visionary", mtgo_id: 23965 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "61")
MagicCard.create(object_type: "vanguard", name: "Avatar - Momir Vig, Simic Visionary (Alt.)", mtgo_id: 37826 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "121")
MagicCard.create(object_type: "vanguard", name: "Avatar - Morinfen", mtgo_id: 28799 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "76")
MagicCard.create(object_type: "vanguard", name: "Avatar - Moriok", mtgo_id: 39011 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "124")
MagicCard.create(object_type: "vanguard", name: "Avatar - Morphling", mtgo_id: 35843 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "112")
MagicCard.create(object_type: "vanguard", name: "Avatar - Murderous Redcap", mtgo_id: 29262 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "80")
MagicCard.create(object_type: "vanguard", name: "Avatar - Nahiri, the Lithomancer", mtgo_id: 54568 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "208")
MagicCard.create(object_type: "vanguard", name: "Avatar - Necropotence", mtgo_id: 30295 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "83")
MagicCard.create(object_type: "vanguard", name: "Avatar - Nekrataal", mtgo_id: 23962 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "58")
MagicCard.create(object_type: "vanguard", name: "Avatar - Nissa, Worldwaker", mtgo_id: 53816 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "203")
MagicCard.create(object_type: "vanguard", name: "Avatar - Niv-Mizzet, Dracogenius", mtgo_id: 46841 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "152")
MagicCard.create(object_type: "vanguard", name: "Avatar - Ob Nixilis, the Fallen", mtgo_id: 35180 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "100")
MagicCard.create(object_type: "vanguard", name: "Avatar - Obzedat, Ghost Council", mtgo_id: 47948 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "156")
MagicCard.create(object_type: "vanguard", name: "Avatar - Oni of Wild Places", mtgo_id: 35 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "50")
MagicCard.create(object_type: "vanguard", name: "Avatar - Orcish Squatters", mtgo_id: 30296 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "84")
MagicCard.create(object_type: "vanguard", name: "Avatar - Peacekeeper", mtgo_id: 28798 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "75")
MagicCard.create(object_type: "vanguard", name: "Avatar - Phage the Untouchable", mtgo_id: 18 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "31")
MagicCard.create(object_type: "vanguard", name: "Avatar - Phyrexian Metamorph", mtgo_id: 40028 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "130")
MagicCard.create(object_type: "vanguard", name: "Avatar - Phyrexian Negator", mtgo_id: 39672 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "129")
MagicCard.create(object_type: "vanguard", name: "Avatar - Platinum Angel", mtgo_id: 25 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "40")
MagicCard.create(object_type: "vanguard", name: "Avatar - Platinum Emperion", mtgo_id: 37825 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "120")
MagicCard.create(object_type: "vanguard", name: "Avatar - Prime Speaker Zegana", mtgo_id: 47952 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "160")
MagicCard.create(object_type: "vanguard", name: "Avatar - Prodigal Sorcerer", mtgo_id: 15 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "17")
MagicCard.create(object_type: "vanguard", name: "Avatar - Prophetic Flamespeaker", mtgo_id: 52544 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "188")
MagicCard.create(object_type: "vanguard", name: "Avatar - Radiant, Archangel", mtgo_id: 36900 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "116")
MagicCard.create(object_type: "vanguard", name: "Avatar - Rakdos, Lord of Riots", mtgo_id: 46843 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "154")
MagicCard.create(object_type: "vanguard", name: "Avatar - Raksha Golden Cub", mtgo_id: 28 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "43")
MagicCard.create(object_type: "vanguard", name: "Avatar - Ravager of the Fells", mtgo_id: 43494 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "146")
MagicCard.create(object_type: "vanguard", name: "Avatar - Reaper King", mtgo_id: 29261 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "79")
MagicCard.create(object_type: "vanguard", name: "Avatar - Riku of Two Reflections", mtgo_id: 41102 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "133")
MagicCard.create(object_type: "vanguard", name: "Avatar - Rith, the Awakener", mtgo_id: 30297 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "85")
MagicCard.create(object_type: "vanguard", name: "Avatar - Rofellos, Llanowar Emissary", mtgo_id: 39671 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "128")
MagicCard.create(object_type: "vanguard", name: "Avatar - Rootwater Thief", mtgo_id: 43047 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "143")
MagicCard.create(object_type: "vanguard", name: "Avatar - Royal Assassin", mtgo_id: 23 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "38")
MagicCard.create(object_type: "vanguard", name: "Avatar - Rumbling Slum", mtgo_id: 41 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "56")
MagicCard.create(object_type: "vanguard", name: "Avatar - Rune-Scarred Demon", mtgo_id: 41620 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "138")
MagicCard.create(object_type: "vanguard", name: "Avatar - Sakashima the Impostor", mtgo_id: 34 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "49")
MagicCard.create(object_type: "vanguard", name: "Avatar - Sarkhan, the Dragonspeaker", mtgo_id: 54485 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "206")
MagicCard.create(object_type: "vanguard", name: "Avatar - Serra Angel", mtgo_id: 9 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "1")
MagicCard.create(object_type: "vanguard", name: "Avatar - Serra Angel (Alt.)", mtgo_id: 32524 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "2")
MagicCard.create(object_type: "vanguard", name: "Avatar - Seshiro the Anointed", mtgo_id: 31 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "46")
MagicCard.create(object_type: "vanguard", name: "Avatar - Sisters of Stone Death", mtgo_id: 40 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "55")
MagicCard.create(object_type: "vanguard", name: "Avatar - Skinshifter", mtgo_id: 41619 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "137")
MagicCard.create(object_type: "vanguard", name: "Avatar - Sliver Queen", mtgo_id: 32101 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "92")
MagicCard.create(object_type: "vanguard", name: "Avatar - Sorin, Solemn Visitor", mtgo_id: 54484 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "205")
MagicCard.create(object_type: "vanguard", name: "Avatar - Spear of the General", mtgo_id: 52545 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "189")
MagicCard.create(object_type: "vanguard", name: "Avatar - Squee, Goblin Nabob", mtgo_id: 26958 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "71")
MagicCard.create(object_type: "vanguard", name: "Avatar - Stalking Tiger", mtgo_id: 11 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "7")
MagicCard.create(object_type: "vanguard", name: "Avatar - Stangg", mtgo_id: 33439 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "99")
MagicCard.create(object_type: "vanguard", name: "Avatar - Steel Overseer", mtgo_id: 37589 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "118")
MagicCard.create(object_type: "vanguard", name: "Avatar - Stonehewer Giant", mtgo_id: 28941 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "77")
MagicCard.create(object_type: "vanguard", name: "Avatar - Stuffy Doll", mtgo_id: 24847 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "65")
MagicCard.create(object_type: "vanguard", name: "Avatar - Talrand, Sky Summoner", mtgo_id: 46019 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "149")
MagicCard.create(object_type: "vanguard", name: "Avatar - Teysa, Orzhov Scion", mtgo_id: 42 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "57")
MagicCard.create(object_type: "vanguard", name: "Avatar - The Avenger", mtgo_id: 50081 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "170")
MagicCard.create(object_type: "vanguard", name: "Avatar - The Champion", mtgo_id: 52551 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "195")
MagicCard.create(object_type: "vanguard", name: "Avatar - The Destined", mtgo_id: 52550 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "194")
MagicCard.create(object_type: "vanguard", name: "Avatar - The Explorer", mtgo_id: 51884 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "183")
MagicCard.create(object_type: "vanguard", name: "Avatar - The General", mtgo_id: 51879 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "178")
MagicCard.create(object_type: "vanguard", name: "Avatar - The Harvester", mtgo_id: 50084 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "173")
MagicCard.create(object_type: "vanguard", name: "Avatar - The Hunter", mtgo_id: 50083 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "172")
MagicCard.create(object_type: "vanguard", name: "Avatar - The Mimeoplasm", mtgo_id: 41105 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "136")
MagicCard.create(object_type: "vanguard", name: "Avatar - The Philosopher", mtgo_id: 50080 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "169")
MagicCard.create(object_type: "vanguard", name: "Avatar - The Protector", mtgo_id: 50079 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "168")
MagicCard.create(object_type: "vanguard", name: "Avatar - The Provider", mtgo_id: 51883 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "182")
MagicCard.create(object_type: "vanguard", name: "Avatar - The Savant", mtgo_id: 51880 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "179")
MagicCard.create(object_type: "vanguard", name: "Avatar - The Slayer", mtgo_id: 50085 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "174")
MagicCard.create(object_type: "vanguard", name: "Avatar - The Tyrant", mtgo_id: 51881 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "180")
MagicCard.create(object_type: "vanguard", name: "Avatar - The Vanquisher", mtgo_id: 51885 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "184")
MagicCard.create(object_type: "vanguard", name: "Avatar - The Warmonger", mtgo_id: 51882 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "181")
MagicCard.create(object_type: "vanguard", name: "Avatar - The Warrior", mtgo_id: 50082 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "171")
MagicCard.create(object_type: "vanguard", name: "Avatar - Tradewind Rider", mtgo_id: 31500 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "89")
MagicCard.create(object_type: "vanguard", name: "Avatar - Transcendent Master", mtgo_id: 36831 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "113")
MagicCard.create(object_type: "vanguard", name: "Avatar - Trostani, Selesnya's Voice", mtgo_id: 46844 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "155")
MagicCard.create(object_type: "vanguard", name: "Avatar - Two-Headed Giant of Foriys", mtgo_id: 21 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "36")
MagicCard.create(object_type: "vanguard", name: "Avatar - Tymaret, the Murder King", mtgo_id: 50077 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "166")
MagicCard.create(object_type: "vanguard", name: "Avatar - Vampire Nocturnus", mtgo_id: 33092 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "97")
MagicCard.create(object_type: "vanguard", name: "Avatar - Viridian Zealot", mtgo_id: 26 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "41")
MagicCard.create(object_type: "vanguard", name: "Avatar - Windreader Sphinx", mtgo_id: 49805 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "164")
MagicCard.create(object_type: "vanguard", name: "Avatar - Withengar Unbound", mtgo_id: 43493 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "145")
MagicCard.create(object_type: "vanguard", name: "Avatar - Word of Command", mtgo_id: 39009 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "122")
MagicCard.create(object_type: "vanguard", name: "Avatar - Zedruu the Greathearted", mtgo_id: 41104 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "135")
MagicCard.create(object_type: "vanguard", name: "Avatar - Zodiac Dragon", mtgo_id: 33438 , magic_set_id: MagicSet.find_by(code: "VAN").id, collector_number: "98")
